/**
 * Mind Mesh V2 Telemetry Types
 *
 * Privacy-preserving telemetry events for Regulation integration.
 *
 * CRITICAL CONTRACT:
 * - Telemetry NEVER captures content (title, body, text)
 * - Telemetry NEVER captures references (IDs to Guardrails entities)
 * - Telemetry NEVER captures relationships (container IDs, node endpoints)
 * - Telemetry ONLY captures structural patterns and behavior
 *
 * Prime Rule: Mind Mesh emits behaviour. Regulation interprets patterns.
 *              Regulation never interprets meaning.
 */

// ============================================================================
// ALLOWED TELEMETRY EVENT TYPES
// ============================================================================

/**
 * Exhaustive list of allowed telemetry event types.
 * These are the ONLY events that can be persisted.
 */
export type TelemetryEventType =
  // Container events
  | 'ContainerCreated'
  | 'ContainerActivated'
  | 'ContainerMoved'
  | 'ContainerResized'
  | 'ContainerNested'
  | 'ContainerUnnested'
  | 'ContainerConverted'
  | 'ContainerHidden'
  | 'ContainerCollapsed'
  | 'ContainerDeleted'
  // Node events
  | 'NodeCreated'
  | 'NodeDeleted'
  | 'NodeTypeChanged'
  | 'NodeDirectionChanged'
  | 'NodeHidden'
  // Layout events
  | 'DefaultLayoutBroken'
  | 'DefaultLayoutReset'
  | 'FocusModeEntered'
  | 'FocusModeExited'
  // Session / lock events
  | 'CanvasLockAcquired'
  | 'CanvasLockReleased'
  | 'WorkspaceOpened'
  | 'WorkspaceClosed';

// ============================================================================
// ALLOWED METADATA FIELDS
// ============================================================================

/**
 * Container type metadata (structural only).
 * NEVER includes container content or references.
 */
export type ContainerTypeMeta = 'ghost' | 'active';

/**
 * Relationship type metadata (structural only).
 * NEVER includes connected entities.
 */
export type RelationshipTypeMeta = 'hierarchy' | 'reference' | 'custom' | 'unknown';

/**
 * Relationship direction metadata (structural only).
 */
export type DirectionMeta = 'forward' | 'bidirectional' | 'reverse';

/**
 * Allowed metadata fields for telemetry events.
 * These are the ONLY fields that can be stored in metadata.
 *
 * FORBIDDEN FIELDS (never allowed):
 * - container title/body
 * - reference IDs (track IDs, task IDs, entity IDs)
 * - connected container IDs
 * - content diffs
 * - labels, filenames, text
 * - anything that reconstructs meaning
 */
export interface AllowedTelemetryMeta {
  /**
   * Container type (ghost vs active).
   * Allowed because it's structural, not semantic.
   */
  containerType?: ContainerTypeMeta;

  /**
   * Relationship type (hierarchy, reference, etc).
   * Allowed because it's categorical, not identifying.
   */
  relationshipType?: RelationshipTypeMeta;

  /**
   * Relationship direction.
   * Allowed because it's structural.
   */
  direction?: DirectionMeta;

  /**
   * Whether container is ghost.
   * Allowed because it's a boolean flag.
   */
  isGhost?: boolean;

  /**
   * Whether node is auto-generated.
   * Allowed because it's a boolean flag.
   */
  isAutoGenerated?: boolean;

  /**
   * Activation reason (categorical).
   * Allowed because it describes interaction type.
   */
  activationReason?: 'user_drag' | 'user_connect_node' | 'user_nest' | 'user_explicit' | 'cascade_from_parent';

  /**
   * Session duration in minutes (aggregate).
   * Allowed because it's an aggregate metric.
   */
  sessionDurationMinutes?: number;

  /**
   * Count of entities (aggregate).
   * Allowed because it's a count, not identifying.
   */
  entityCount?: number;
}

// ============================================================================
// TELEMETRY EVENT STRUCTURE
// ============================================================================

/**
 * Core telemetry event structure.
 * Contains ONLY allowed fields.
 *
 * CRITICAL: This is the contract between Mind Mesh and Regulation.
 * Any violation of this contract breaks privacy guarantees.
 */
export interface TelemetryEvent {
  /**
   * Unique event ID (generated)
   */
  id: string;

  /**
   * Workspace ID (for scoping)
   */
  workspaceId: string;

  /**
   * User ID (for attribution)
   */
  userId: string;

  /**
   * Event type (from allowed list)
   */
  eventType: TelemetryEventType;

  /**
   * Event timestamp
   */
  timestamp: string;

  /**
   * Allowed metadata fields only.
   * Validated before persistence.
   */
  meta: AllowedTelemetryMeta;
}

// ============================================================================
// DATABASE ROW TYPES
// ============================================================================

/**
 * Database row for telemetry events.
 * Matches mind_mesh_telemetry_events table schema.
 */
export interface TelemetryEventRow {
  id: string;
  workspace_id: string;
  user_id: string;
  event_type: TelemetryEventType;
  timestamp: string;
  meta: AllowedTelemetryMeta;
  created_at: string;
}

/**
 * Input for creating telemetry event (database insert).
 */
export interface TelemetryEventInsert {
  workspace_id: string;
  user_id: string;
  event_type: TelemetryEventType;
  timestamp: string;
  meta: AllowedTelemetryMeta;
}

// ============================================================================
// AGGREGATION TYPES
// ============================================================================

/**
 * Daily activity summary (descriptive only).
 * NO scoring, NO judgments, NO recommendations.
 */
export interface DailyActivitySummary {
  workspaceId: string;
  userId: string;
  date: string;

  /**
   * Event counts by type.
   * Descriptive metric: shows what happened.
   */
  eventCounts: Record<TelemetryEventType, number>;

  /**
   * Total containers activated.
   * Descriptive metric: shows activation volume.
   */
  containersActivated: number;

  /**
   * Total nodes created.
   * Descriptive metric: shows connection volume.
   */
  nodesCreated: number;

  /**
   * Estimated session duration in minutes.
   * Based on workspace open/close or lock acquire/release.
   * Descriptive metric: shows engagement duration.
   */
  sessionMinutes: number;

  /**
   * Total events recorded.
   * Descriptive metric: shows activity level.
   */
  totalEvents: number;
}

/**
 * Weekly pattern summary (descriptive only).
 * NO scoring, NO judgments, NO recommendations.
 */
export interface WeeklyPatternSummary {
  workspaceId: string;
  userId: string;
  weekStart: string;
  weekEnd: string;

  /**
   * Daily event counts (7 days).
   * Descriptive metric: shows activity distribution.
   */
  dailyCounts: Array<{
    date: string;
    eventCount: number;
  }>;

  /**
   * Creation burst detection (rapid sequences).
   * Descriptive metric: identifies periods of rapid creation.
   * Burst = 5+ creation events within 5 minutes.
   */
  creationBursts: Array<{
    timestamp: string;
    eventCount: number;
  }>;

  /**
   * Layout break count.
   * Descriptive metric: shows manual intervention frequency.
   */
  layoutBreaks: number;

  /**
   * Total session minutes across week.
   * Descriptive metric: shows total engagement.
   */
  totalSessionMinutes: number;

  /**
   * Most active day of week.
   * Descriptive metric: shows usage pattern.
   */
  mostActiveDay: string;
}

// ============================================================================
// VALIDATION HELPERS
// ============================================================================

/**
 * Checks if an event type is allowed.
 */
export function isAllowedEventType(eventType: string): eventType is TelemetryEventType {
  const allowed: TelemetryEventType[] = [
    'ContainerCreated',
    'ContainerActivated',
    'ContainerMoved',
    'ContainerResized',
    'ContainerNested',
    'ContainerUnnested',
    'ContainerConverted',
    'ContainerHidden',
    'ContainerCollapsed',
    'ContainerDeleted',
    'NodeCreated',
    'NodeDeleted',
    'NodeTypeChanged',
    'NodeDirectionChanged',
    'NodeHidden',
    'DefaultLayoutBroken',
    'DefaultLayoutReset',
    'FocusModeEntered',
    'FocusModeExited',
    'CanvasLockAcquired',
    'CanvasLockReleased',
    'WorkspaceOpened',
    'WorkspaceClosed',
  ];

  return allowed.includes(eventType as TelemetryEventType);
}

/**
 * Checks if a metadata field is allowed.
 */
export function isAllowedMetaField(field: string): boolean {
  const allowed = [
    'containerType',
    'relationshipType',
    'direction',
    'isGhost',
    'isAutoGenerated',
    'activationReason',
    'sessionDurationMinutes',
    'entityCount',
  ];

  return allowed.includes(field);
}

/**
 * Validates that metadata contains ONLY allowed fields.
 * Returns validation errors if forbidden fields detected.
 */
export function validateTelemetryMeta(meta: Record<string, unknown>): {
  valid: boolean;
  errors: string[];
  forbiddenFields: string[];
} {
  const errors: string[] = [];
  const forbiddenFields: string[] = [];

  for (const field of Object.keys(meta)) {
    if (!isAllowedMetaField(field)) {
      errors.push(`Forbidden metadata field: ${field}`);
      forbiddenFields.push(field);
    }
  }

  // Check for forbidden values (attempts to sneak content)
  const metaStr = JSON.stringify(meta);
  if (metaStr.includes('title') || metaStr.includes('body') || metaStr.includes('content')) {
    errors.push('Metadata contains forbidden content-related keys');
  }

  return {
    valid: errors.length === 0,
    errors,
    forbiddenFields,
  };
}

/**
 * Validates complete telemetry event structure.
 */
export function validateTelemetryEvent(event: TelemetryEvent): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  // Check required fields
  if (!event.id) errors.push('Missing id');
  if (!event.workspaceId) errors.push('Missing workspaceId');
  if (!event.userId) errors.push('Missing userId');
  if (!event.eventType) errors.push('Missing eventType');
  if (!event.timestamp) errors.push('Missing timestamp');

  // Check event type is allowed
  if (event.eventType && !isAllowedEventType(event.eventType)) {
    errors.push(`Invalid event type: ${event.eventType}`);
  }

  // Validate metadata
  if (event.meta) {
    const metaValidation = validateTelemetryMeta(event.meta as Record<string, unknown>);
    if (!metaValidation.valid) {
      errors.push(...metaValidation.errors);
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

// ============================================================================
// TYPE GUARDS
// ============================================================================

/**
 * Type guard for telemetry event.
 */
export function isTelemetryEvent(obj: unknown): obj is TelemetryEvent {
  if (!obj || typeof obj !== 'object') return false;

  const event = obj as TelemetryEvent;
  return (
    typeof event.id === 'string' &&
    typeof event.workspaceId === 'string' &&
    typeof event.userId === 'string' &&
    isAllowedEventType(event.eventType) &&
    typeof event.timestamp === 'string' &&
    typeof event.meta === 'object'
  );
}

/**
 * Type guard for allowed metadata.
 */
export function isAllowedTelemetryMeta(obj: unknown): obj is AllowedTelemetryMeta {
  if (!obj || typeof obj !== 'object') return false;

  const meta = obj as Record<string, unknown>;
  for (const field of Object.keys(meta)) {
    if (!isAllowedMetaField(field)) return false;
  }

  return true;
}
