import type { PantryItemType } from './intelligentGrocery';

export interface PantryStarterItem {
  name: string;
  category?: string | null;
  description?: string;
  pantryType: PantryItemType;
  estimatedCost?: number | null;
}

export interface PantryStarterSection {
  title: string;
  description?: string;
  items: PantryStarterItem[];
}

const normalizeStarterName = (value: string) =>
  value.trim().toLowerCase().replace(/[^a-z0-9]+/g, ' ').replace(/\s+/g, ' ').trim();

const STARTER_ESTIMATED_COSTS: Record<string, number> = {
  [normalizeStarterName('Chopped Tomatoes')]: 0.75,
  [normalizeStarterName('Tomato Puree')]: 0.65,
  [normalizeStarterName('Passata')]: 0.95,
  [normalizeStarterName('Pasta Sauce')]: 1.45,
  [normalizeStarterName('Chickpeas')]: 0.75,
  [normalizeStarterName('Kidney Beans')]: 0.8,
  [normalizeStarterName('Butter Beans')]: 0.85,
  [normalizeStarterName('Black Beans')]: 0.9,
  [normalizeStarterName('Baked Beans')]: 0.95,
  [normalizeStarterName('Sweetcorn')]: 0.8,
  [normalizeStarterName('Peas')]: 0.8,
  [normalizeStarterName('Carrots')]: 0.55,
  [normalizeStarterName('Coconut Milk')]: 1.35,
  [normalizeStarterName('Soup')]: 1.2,
  [normalizeStarterName('Tuna')]: 1.2,
  [normalizeStarterName('Sardines')]: 0.95,
  [normalizeStarterName('Corned Beef')]: 2.8,
  [normalizeStarterName('Jam')]: 1.6,
  [normalizeStarterName('Honey')]: 2.5,
  [normalizeStarterName('Peanut Butter')]: 1.85,
  [normalizeStarterName('Rice')]: 1.5,
  [normalizeStarterName('Microwave Rice')]: 0.8,
  [normalizeStarterName('Pasta')]: 0.95,
  [normalizeStarterName('Spaghetti')]: 0.95,
  [normalizeStarterName('Noodles')]: 1.0,
  [normalizeStarterName('Couscous')]: 1.2,
  [normalizeStarterName('Quinoa')]: 2.6,
  [normalizeStarterName('Lentils')]: 1.65,
  [normalizeStarterName('Red Lentils')]: 1.7,
  [normalizeStarterName('Flour')]: 0.95,
  [normalizeStarterName('Self Raising Flour')]: 0.95,
  [normalizeStarterName('Plain Flour')]: 0.9,
  [normalizeStarterName('Sugar')]: 1.15,
  [normalizeStarterName('Brown Sugar')]: 1.35,
  [normalizeStarterName('Salt')]: 0.65,
  [normalizeStarterName('Black Pepper')]: 1.3,
  [normalizeStarterName('Olive Oil')]: 4.95,
  [normalizeStarterName('Vegetable Oil')]: 2.45,
  [normalizeStarterName('Stock Cubes')]: 0.85,
  [normalizeStarterName('Gravy Granules')]: 1.75,
  [normalizeStarterName('Porridge Oats')]: 1.4,
  [normalizeStarterName('Cereal')]: 2.3,
  [normalizeStarterName('Granola')]: 2.8,
  [normalizeStarterName('Crackers')]: 1.3,
  [normalizeStarterName('Biscuits')]: 1.35,
  [normalizeStarterName('Breakfast Bars')]: 1.8,
  [normalizeStarterName('Nuts')]: 2.3,
  [normalizeStarterName('Dried Fruit')]: 1.75,
  [normalizeStarterName('Tea')]: 2.1,
  [normalizeStarterName('Coffee')]: 3.95,
  [normalizeStarterName('Hot Chocolate')]: 2.2,
  [normalizeStarterName('Long Life Milk')]: 1.2,
  [normalizeStarterName('Juice Cartons')]: 1.1,
  [normalizeStarterName('Squash')]: 1.5,
  [normalizeStarterName('Bottled Water')]: 3.5,
  [normalizeStarterName('Milk')]: 1.6,
  [normalizeStarterName('Eggs')]: 2.25,
  [normalizeStarterName('Butter')]: 2.1,
  [normalizeStarterName('Margarine')]: 1.45,
  [normalizeStarterName('Cheese')]: 2.75,
  [normalizeStarterName('Grated Cheese')]: 2.5,
  [normalizeStarterName('Yogurt')]: 2.0,
  [normalizeStarterName('Cream')]: 1.2,
  [normalizeStarterName('Bread')]: 1.45,
  [normalizeStarterName('Wraps')]: 1.6,
  [normalizeStarterName('Bagels')]: 1.8,
  [normalizeStarterName('Ham')]: 2.2,
  [normalizeStarterName('Chicken Breast')]: 4.25,
  [normalizeStarterName('Mince')]: 3.95,
  [normalizeStarterName('Bacon')]: 2.85,
  [normalizeStarterName('Sausages')]: 2.7,
  [normalizeStarterName('Bag of Potatoes')]: 1.95,
  [normalizeStarterName('Onions')]: 1.1,
  [normalizeStarterName('Garlic')]: 0.6,
  [normalizeStarterName('Peppers')]: 1.65,
  [normalizeStarterName('Broccoli')]: 0.95,
  [normalizeStarterName('Cucumber')]: 0.8,
  [normalizeStarterName('Tomatoes')]: 1.45,
  [normalizeStarterName('Lettuce')]: 0.85,
  [normalizeStarterName('Apples')]: 1.9,
  [normalizeStarterName('Bananas')]: 1.1,
  [normalizeStarterName('Oranges')]: 1.9,
  [normalizeStarterName('Frozen Peas')]: 1.55,
  [normalizeStarterName('Frozen Sweetcorn')]: 1.45,
  [normalizeStarterName('Frozen Chips')]: 2.35,
  [normalizeStarterName('Frozen Pizza')]: 3.25,
  [normalizeStarterName('Frozen Fish Fingers')]: 2.95,
  [normalizeStarterName('Frozen Chicken Nuggets')]: 2.9,
  [normalizeStarterName('Toilet Roll')]: 4.75,
  [normalizeStarterName('Kitchen Roll')]: 2.6,
  [normalizeStarterName('Tissues')]: 1.2,
  [normalizeStarterName('Baby Wipes')]: 0.95,
  [normalizeStarterName('Bin Bags')]: 2.3,
  [normalizeStarterName('Foil')]: 1.8,
  [normalizeStarterName('Cling Film')]: 1.35,
  [normalizeStarterName('Baking Paper')]: 1.55,
  [normalizeStarterName('Washing Up Liquid')]: 1.2,
  [normalizeStarterName('Dishwasher Tablets')]: 4.95,
  [normalizeStarterName('Laundry Detergent')]: 5.5,
  [normalizeStarterName('Fabric Softener')]: 2.8,
  [normalizeStarterName('Hand Soap')]: 1.15,
  [normalizeStarterName('Bleach')]: 1.0,
  [normalizeStarterName('Multi Surface Spray')]: 1.75,
  [normalizeStarterName('Sponges')]: 1.2,
  [normalizeStarterName('Toothpaste')]: 1.75,
  [normalizeStarterName('Shampoo')]: 2.95,
  [normalizeStarterName('Soap Bars')]: 1.2,
  [normalizeStarterName('Batteries')]: 4.5,
};

export function getPantryStarterEstimatedCost(itemName: string): number | null {
  if (!itemName) return null;
  return STARTER_ESTIMATED_COSTS[normalizeStarterName(itemName)] ?? null;
}

const withStarterMeta = (item: PantryStarterItem): PantryStarterItem => ({
  ...item,
  estimatedCost: item.estimatedCost ?? getPantryStarterEstimatedCost(item.name),
});

export const PANTRY_QUICK_PICK_ITEMS: PantryStarterItem[] = [
  { name: 'Chopped Tomatoes', category: 'pantry', pantryType: 'long_life', description: '400g can staple' },
  { name: 'Chickpeas', category: 'pantry', pantryType: 'long_life', description: 'Useful for curries and salads' },
  { name: 'Kidney Beans', category: 'pantry', pantryType: 'long_life', description: 'Good for chilli and stews' },
  { name: 'Baked Beans', category: 'pantry', pantryType: 'long_life', description: 'Quick long-life meal' },
  { name: 'Soup', category: 'pantry', pantryType: 'long_life', description: 'Easy cupboard backup' },
  { name: 'Tuna', category: 'pantry', pantryType: 'long_life', description: 'Protein staple' },
  { name: 'Rice', category: 'pantry', pantryType: 'long_life', description: 'Core dry staple' },
  { name: 'Pasta', category: 'pantry', pantryType: 'long_life', description: 'Cupboard essential' },
  { name: 'Porridge Oats', category: 'pantry', pantryType: 'long_life', description: 'Breakfast basic' },
  { name: 'Peanut Butter', category: 'pantry', pantryType: 'long_life', description: 'Long-life spread' },
  { name: 'Tea', category: 'beverages', pantryType: 'long_life', description: 'Daily drink staple' },
  { name: 'Coffee', category: 'beverages', pantryType: 'long_life', description: 'Daily drink staple' },
  { name: 'Milk', category: 'dairy', pantryType: 'perishable', description: 'Fresh fridge essential' },
  { name: 'Eggs', category: 'dairy', pantryType: 'perishable', description: 'Flexible fridge staple' },
  { name: 'Bread', category: 'bakery', pantryType: 'perishable', description: 'Everyday fresh staple' },
  { name: 'Bag of Potatoes', category: 'produce', pantryType: 'perishable', description: 'Typical 2.5kg bag' },
  { name: 'Onions', category: 'produce', pantryType: 'perishable', description: 'Base ingredient' },
  { name: 'Toilet Roll', category: 'household', pantryType: 'non_food', description: 'Household stock staple' },
  { name: 'Kitchen Roll', category: 'household', pantryType: 'non_food', description: 'Household stock staple' },
  { name: 'Washing Up Liquid', category: 'household', pantryType: 'non_food', description: 'Cleaning essential' },
].map(withStarterMeta);

export const PANTRY_STARTER_SECTIONS: PantryStarterSection[] = [
  {
    title: 'Cupboard Basics',
    description: 'Core dry goods and long-life staples you are likely to replace often.',
    items: [
      { name: 'Rice', category: 'pantry', pantryType: 'long_life' },
      { name: 'Microwave Rice', category: 'pantry', pantryType: 'long_life' },
      { name: 'Pasta', category: 'pantry', pantryType: 'long_life' },
      { name: 'Spaghetti', category: 'pantry', pantryType: 'long_life' },
      { name: 'Noodles', category: 'pantry', pantryType: 'long_life' },
      { name: 'Couscous', category: 'pantry', pantryType: 'long_life' },
      { name: 'Quinoa', category: 'pantry', pantryType: 'long_life' },
      { name: 'Lentils', category: 'pantry', pantryType: 'long_life' },
      { name: 'Red Lentils', category: 'pantry', pantryType: 'long_life' },
      { name: 'Flour', category: 'pantry', pantryType: 'long_life' },
      { name: 'Self Raising Flour', category: 'pantry', pantryType: 'long_life' },
      { name: 'Plain Flour', category: 'pantry', pantryType: 'long_life' },
      { name: 'Sugar', category: 'pantry', pantryType: 'long_life' },
      { name: 'Brown Sugar', category: 'pantry', pantryType: 'long_life' },
      { name: 'Salt', category: 'pantry', pantryType: 'long_life' },
      { name: 'Black Pepper', category: 'pantry', pantryType: 'long_life' },
      { name: 'Olive Oil', category: 'pantry', pantryType: 'long_life' },
      { name: 'Vegetable Oil', category: 'pantry', pantryType: 'long_life' },
      { name: 'Stock Cubes', category: 'pantry', pantryType: 'long_life' },
      { name: 'Gravy Granules', category: 'pantry', pantryType: 'long_life' },
    ],
  },
  {
    title: 'Tins, Jars And Ready Meals',
    description: 'Useful back-up foods, quick proteins, canned vegetables, and sauces.',
    items: [
      { name: 'Chopped Tomatoes', category: 'pantry', pantryType: 'long_life' },
      { name: 'Tomato Puree', category: 'pantry', pantryType: 'long_life' },
      { name: 'Passata', category: 'pantry', pantryType: 'long_life' },
      { name: 'Pasta Sauce', category: 'pantry', pantryType: 'long_life' },
      { name: 'Chickpeas', category: 'pantry', pantryType: 'long_life' },
      { name: 'Kidney Beans', category: 'pantry', pantryType: 'long_life' },
      { name: 'Butter Beans', category: 'pantry', pantryType: 'long_life' },
      { name: 'Black Beans', category: 'pantry', pantryType: 'long_life' },
      { name: 'Baked Beans', category: 'pantry', pantryType: 'long_life' },
      { name: 'Sweetcorn', category: 'pantry', pantryType: 'long_life' },
      { name: 'Peas', category: 'pantry', pantryType: 'long_life' },
      { name: 'Carrots', category: 'pantry', pantryType: 'long_life' },
      { name: 'Coconut Milk', category: 'pantry', pantryType: 'long_life' },
      { name: 'Soup', category: 'pantry', pantryType: 'long_life' },
      { name: 'Tuna', category: 'pantry', pantryType: 'long_life' },
      { name: 'Sardines', category: 'pantry', pantryType: 'long_life' },
      { name: 'Corned Beef', category: 'pantry', pantryType: 'long_life' },
      { name: 'Jam', category: 'pantry', pantryType: 'long_life' },
      { name: 'Honey', category: 'pantry', pantryType: 'long_life' },
      { name: 'Peanut Butter', category: 'pantry', pantryType: 'long_life' },
    ],
  },
  {
    title: 'Breakfast, Snacks And Drinks',
    description: 'Everyday quick options for mornings, packed lunches, and hot drinks.',
    items: [
      { name: 'Porridge Oats', category: 'pantry', pantryType: 'long_life' },
      { name: 'Cereal', category: 'pantry', pantryType: 'long_life' },
      { name: 'Granola', category: 'pantry', pantryType: 'long_life' },
      { name: 'Crackers', category: 'snacks', pantryType: 'long_life' },
      { name: 'Biscuits', category: 'snacks', pantryType: 'long_life' },
      { name: 'Breakfast Bars', category: 'snacks', pantryType: 'long_life' },
      { name: 'Nuts', category: 'snacks', pantryType: 'long_life' },
      { name: 'Dried Fruit', category: 'snacks', pantryType: 'long_life' },
      { name: 'Tea', category: 'beverages', pantryType: 'long_life' },
      { name: 'Coffee', category: 'beverages', pantryType: 'long_life' },
      { name: 'Hot Chocolate', category: 'beverages', pantryType: 'long_life' },
      { name: 'Long Life Milk', category: 'beverages', pantryType: 'long_life' },
      { name: 'Juice Cartons', category: 'beverages', pantryType: 'long_life' },
      { name: 'Squash', category: 'beverages', pantryType: 'long_life' },
      { name: 'Bottled Water', category: 'beverages', pantryType: 'long_life' },
    ],
  },
  {
    title: 'Fresh And Chilled',
    description: 'Fridge staples and short-life foods you regularly rotate.',
    items: [
      { name: 'Milk', category: 'dairy', pantryType: 'perishable' },
      { name: 'Eggs', category: 'dairy', pantryType: 'perishable' },
      { name: 'Butter', category: 'dairy', pantryType: 'perishable' },
      { name: 'Margarine', category: 'dairy', pantryType: 'perishable' },
      { name: 'Cheese', category: 'dairy', pantryType: 'perishable' },
      { name: 'Grated Cheese', category: 'dairy', pantryType: 'perishable' },
      { name: 'Yogurt', category: 'dairy', pantryType: 'perishable' },
      { name: 'Cream', category: 'dairy', pantryType: 'perishable' },
      { name: 'Bread', category: 'bakery', pantryType: 'perishable' },
      { name: 'Wraps', category: 'bakery', pantryType: 'perishable' },
      { name: 'Bagels', category: 'bakery', pantryType: 'perishable' },
      { name: 'Ham', category: 'meat', pantryType: 'perishable' },
      { name: 'Chicken Breast', category: 'meat', pantryType: 'perishable' },
      { name: 'Mince', category: 'meat', pantryType: 'perishable' },
      { name: 'Bacon', category: 'meat', pantryType: 'perishable' },
      { name: 'Sausages', category: 'meat', pantryType: 'perishable' },
    ],
  },
  {
    title: 'Produce And Freezer',
    description: 'Fruit, vegetables, and frozen backups that support day-to-day meals.',
    items: [
      { name: 'Bag of Potatoes', category: 'produce', pantryType: 'perishable' },
      { name: 'Onions', category: 'produce', pantryType: 'perishable' },
      { name: 'Garlic', category: 'produce', pantryType: 'perishable' },
      { name: 'Carrots', category: 'produce', pantryType: 'perishable' },
      { name: 'Peppers', category: 'produce', pantryType: 'perishable' },
      { name: 'Broccoli', category: 'produce', pantryType: 'perishable' },
      { name: 'Cucumber', category: 'produce', pantryType: 'perishable' },
      { name: 'Tomatoes', category: 'produce', pantryType: 'perishable' },
      { name: 'Lettuce', category: 'produce', pantryType: 'perishable' },
      { name: 'Apples', category: 'produce', pantryType: 'perishable' },
      { name: 'Bananas', category: 'produce', pantryType: 'perishable' },
      { name: 'Oranges', category: 'produce', pantryType: 'perishable' },
      { name: 'Frozen Peas', category: 'frozen', pantryType: 'perishable' },
      { name: 'Frozen Sweetcorn', category: 'frozen', pantryType: 'perishable' },
      { name: 'Frozen Chips', category: 'frozen', pantryType: 'perishable' },
      { name: 'Frozen Pizza', category: 'frozen', pantryType: 'perishable' },
      { name: 'Frozen Fish Fingers', category: 'frozen', pantryType: 'perishable' },
      { name: 'Frozen Chicken Nuggets', category: 'frozen', pantryType: 'perishable' },
    ],
  },
  {
    title: 'Household And Non-Food',
    description: 'Cleaning, paper goods, hygiene, and practical household backups.',
    items: [
      { name: 'Toilet Roll', category: 'household', pantryType: 'non_food' },
      { name: 'Kitchen Roll', category: 'household', pantryType: 'non_food' },
      { name: 'Tissues', category: 'household', pantryType: 'non_food' },
      { name: 'Baby Wipes', category: 'household', pantryType: 'non_food' },
      { name: 'Bin Bags', category: 'household', pantryType: 'non_food' },
      { name: 'Foil', category: 'household', pantryType: 'non_food' },
      { name: 'Cling Film', category: 'household', pantryType: 'non_food' },
      { name: 'Baking Paper', category: 'household', pantryType: 'non_food' },
      { name: 'Washing Up Liquid', category: 'household', pantryType: 'non_food' },
      { name: 'Dishwasher Tablets', category: 'household', pantryType: 'non_food' },
      { name: 'Laundry Detergent', category: 'household', pantryType: 'non_food' },
      { name: 'Fabric Softener', category: 'household', pantryType: 'non_food' },
      { name: 'Hand Soap', category: 'household', pantryType: 'non_food' },
      { name: 'Bleach', category: 'household', pantryType: 'non_food' },
      { name: 'Multi Surface Spray', category: 'household', pantryType: 'non_food' },
      { name: 'Sponges', category: 'household', pantryType: 'non_food' },
      { name: 'Toothpaste', category: 'household', pantryType: 'non_food' },
      { name: 'Shampoo', category: 'household', pantryType: 'non_food' },
      { name: 'Soap Bars', category: 'household', pantryType: 'non_food' },
      { name: 'Batteries', category: 'household', pantryType: 'non_food' },
    ],
  },
].map((section) => ({
  ...section,
  items: section.items.map(withStarterMeta),
}));
