/**
 * Intelligent Task Library
 * 
 * A comprehensive, searchable library of pre-populated tasks with breakdown steps
 * designed for ADHD users. Tasks are modular, permission-based, and reduce
 * executive function load.
 */

import type { WidgetType } from './fridgeCanvasTypes';

export interface TaskTemplate {
  id: string;
  title: string;
  emoji: string;
  category: TaskCategory;
  keywords: string[]; // For search matching
  steps: string[];
  difficulty: 'easy' | 'medium' | 'hard';
  estimatedTime?: string; // Optional, e.g., "5 min", "15 min"
  linkedWidgetType?: WidgetType; // Widget this task relates to (e.g., 'journal' for "Write in journal")
  linkedWidgetLabel?: string; // Human-readable widget name (e.g., "Journal")
}

export type TaskCategory = 
  | 'self-care'
  | 'cleaning'
  | 'admin'
  | 'health'
  | 'social'
  | 'creative'
  | 'learning'
  | 'organization'
  | 'mindfulness'
  | 'movement'
  | 'nutrition'
  | 'hygiene'
  | 'communication'
  | 'planning'
  | 'maintenance';

export const TASK_LIBRARY: TaskTemplate[] = [
  // ============================================================================
  // SELF-CARE
  // ============================================================================
  {
    id: 'breathe',
    title: 'Take 3 slow breaths',
    emoji: '🫁',
    category: 'self-care',
    keywords: ['breathe', 'breath', 'calm', 'relax', 'pause', 'mindful'],
    steps: [
      'Sit or stand comfortably',
      'Take a slow breath in through your nose',
      'Hold for a moment',
      'Exhale slowly through your mouth',
      'Repeat two more times',
    ],
    difficulty: 'easy',
    estimatedTime: '1 min',
  },
  {
    id: 'water',
    title: 'Drink a glass of water',
    emoji: '💧',
    category: 'self-care',
    keywords: ['water', 'drink', 'hydrate', 'thirsty', 'hydration'],
    steps: [
      'Get a glass or bottle',
      'Fill it with water',
      'Take a few sips',
      'Notice how you feel',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'stretch',
    title: 'Do 3 gentle stretches',
    emoji: '🧘',
    category: 'self-care',
    keywords: ['stretch', 'movement', 'body', 'flexibility', 'tension'],
    steps: [
      'Stand up or sit comfortably',
      'Reach your arms up and hold for 10 seconds',
      'Roll your shoulders back 3 times',
      'Take a deep breath and notice how you feel',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'gratitude',
    title: 'Notice one thing you\'re grateful for',
    emoji: '🙏',
    category: 'self-care',
    keywords: ['gratitude', 'thankful', 'appreciate', 'positive', 'mindful'],
    steps: [
      'Pause for a moment',
      'Think of one thing that went well today',
      'Or one person you appreciate',
      'Take a moment to feel that gratitude',
    ],
    difficulty: 'easy',
    estimatedTime: '1 min',
  },
  {
    id: 'rest',
    title: 'Take a 10-minute rest',
    emoji: '😴',
    category: 'self-care',
    keywords: ['rest', 'nap', 'break', 'recharge', 'pause'],
    steps: [
      'Find a comfortable spot',
      'Set a timer for 10 minutes',
      'Close your eyes or just relax',
      'Get up when the timer goes off',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'comfort-item',
    title: 'Do something comforting',
    emoji: '🫶',
    category: 'self-care',
    keywords: ['comfort', 'cozy', 'warm', 'safe', 'calm'],
    steps: [
      'Think of one thing that comforts you',
      'It could be a blanket, tea, or music',
      'Do that thing for 5 minutes',
      'Notice how you feel',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'set-boundary',
    title: 'Set a boundary',
    emoji: '🛡️',
    category: 'self-care',
    keywords: ['boundary', 'limit', 'protect', 'say no', 'self-care'],
    steps: [
      'Think of one thing you need to say no to',
      'Write down what you\'ll say',
      'Practice saying it out loud',
      'You can send it later if needed',
    ],
    difficulty: 'medium',
    estimatedTime: '5 min',
  },
  {
    id: 'affirmation',
    title: 'Say one kind thing to yourself',
    emoji: '💝',
    category: 'self-care',
    keywords: ['affirmation', 'kindness', 'self-love', 'positive', 'encourage'],
    steps: [
      'Pause for a moment',
      'Think of one thing you did well today',
      'Or one thing you like about yourself',
      'Say it out loud or write it down',
    ],
    difficulty: 'easy',
    estimatedTime: '1 min',
  },

  // ============================================================================
  // CLEANING & TIDYING
  // ============================================================================
  {
    id: 'tidy-surface',
    title: 'Tidy one surface',
    emoji: '🧹',
    category: 'cleaning',
    keywords: ['tidy', 'surface', 'desk', 'table', 'counter', 'clear'],
    steps: [
      'Pick one surface (desk, table, counter)',
      'Pick up 3 items that don\'t belong',
      'Put them where they go (or in a "deal with later" box)',
      'Notice the difference',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'clean-room',
    title: 'Clean my room',
    emoji: '🧹',
    category: 'cleaning',
    keywords: ['clean', 'room', 'bedroom', 'space', 'organize', 'tidy'],
    steps: [
      'Pick one area to focus on',
      'Pick up 3 items that don\'t belong',
      'Make a laundry pile',
      'Clear one surface',
      'Pause and notice what you did',
    ],
    difficulty: 'medium',
    estimatedTime: '15 min',
  },
  {
    id: 'put-away-items',
    title: 'Put away 3 items',
    emoji: '📦',
    category: 'cleaning',
    keywords: ['put away', 'organize', 'items', 'belongings', 'tidy'],
    steps: [
      'Look around for 3 items out of place',
      'Pick up the first item',
      'Put it where it belongs',
      'Repeat for the other 2 items',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'make-bed',
    title: 'Make the bed',
    emoji: '🛏️',
    category: 'cleaning',
    keywords: ['bed', 'make bed', 'sheets', 'bedroom'],
    steps: [
      'Straighten the bottom sheet',
      'Pull up the top sheet',
      'Fluff the pillow',
      'That\'s it - done enough!',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'do-dishes',
    title: 'Wash a few dishes',
    emoji: '🍽️',
    category: 'cleaning',
    keywords: ['dishes', 'wash', 'kitchen', 'sink', 'clean'],
    steps: [
      'Put on some music or a podcast',
      'Wash 3-5 dishes',
      'Rinse and put in drying rack',
      'You can stop here or do more',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'take-trash',
    title: 'Take out the trash',
    emoji: '🗑️',
    category: 'cleaning',
    keywords: ['trash', 'garbage', 'bin', 'take out', 'dispose'],
    steps: [
      'Tie up the trash bag',
      'Take it to the bin outside',
      'Put in a new bag if needed',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'laundry-pile',
    title: 'Sort laundry into one pile',
    emoji: '👕',
    category: 'cleaning',
    keywords: ['laundry', 'clothes', 'wash', 'dirty', 'sort'],
    steps: [
      'Gather clothes from around the room',
      'Put them in one pile or basket',
      'You don\'t have to wash them yet',
      'Just getting them together is enough',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'vacuum-room',
    title: 'Vacuum one room',
    emoji: '🧹',
    category: 'cleaning',
    keywords: ['vacuum', 'sweep', 'floor', 'clean', 'room'],
    steps: [
      'Get the vacuum or broom',
      'Pick one room',
      'Vacuum or sweep the main areas',
      'Put the vacuum away',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'clean-bathroom',
    title: 'Quick bathroom clean',
    emoji: '🚽',
    category: 'cleaning',
    keywords: ['bathroom', 'toilet', 'sink', 'mirror', 'clean'],
    steps: [
      'Spray cleaner on the sink',
      'Wipe the mirror',
      'Quick wipe of the toilet',
      'Done - no need to deep clean',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'wipe-surfaces',
    title: 'Wipe down kitchen surfaces',
    emoji: '🧽',
    category: 'cleaning',
    keywords: ['wipe', 'kitchen', 'counter', 'surface', 'clean'],
    steps: [
      'Get a damp cloth or wipe',
      'Wipe the counter',
      'Wipe the stove top',
      'Put the cloth in the laundry',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'organize-shoes',
    title: 'Organize shoes by the door',
    emoji: '👟',
    category: 'cleaning',
    keywords: ['shoes', 'organize', 'tidy', 'entry', 'door'],
    steps: [
      'Gather shoes by the door',
      'Put pairs together',
      'Line them up or put in a basket',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'clear-desk',
    title: 'Clear off your desk',
    emoji: '🖥️',
    category: 'cleaning',
    keywords: ['desk', 'workspace', 'clear', 'organize', 'tidy'],
    steps: [
      'Pick up 5 items from your desk',
      'Put 3 away where they belong',
      'Put 2 in a "deal with later" spot',
      'Notice the cleared space',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'dust-surfaces',
    title: 'Dust one surface',
    emoji: '🧹',
    category: 'cleaning',
    keywords: ['dust', 'wipe', 'surface', 'furniture', 'clean'],
    steps: [
      'Get a duster or damp cloth',
      'Pick one surface (table, shelf, etc.)',
      'Wipe it down',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },

  // ============================================================================
  // ADMIN & PAPERWORK
  // ============================================================================
  {
    id: 'check-email',
    title: 'Check email',
    emoji: '📧',
    category: 'admin',
    keywords: ['email', 'inbox', 'messages', 'mail', 'check'],
    steps: [
      'Open your email',
      'Read just the first 3 emails',
      'Reply to one if it\'s quick',
      'Close it - you can come back later',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'reply-email',
    title: 'Reply to an email',
    emoji: '✉️',
    category: 'admin',
    keywords: ['reply', 'email', 'respond', 'message', 'answer'],
    steps: [
      'Open the email you need to reply to',
      'Read just the first paragraph',
      'Write one short reply or note',
      'Send it or save as draft',
    ],
    difficulty: 'medium',
    estimatedTime: '10 min',
  },
  {
    id: 'pay-bill',
    title: 'Pay a bill',
    emoji: '💳',
    category: 'admin',
    keywords: ['bill', 'pay', 'payment', 'invoice', 'money'],
    steps: [
      'Find the bill or login to the website',
      'Check the amount due',
      'Enter payment info or schedule payment',
      'Confirm and you\'re done',
    ],
    difficulty: 'medium',
    estimatedTime: '10 min',
  },
  {
    id: 'fill-form',
    title: 'Fill out a form',
    emoji: '📄',
    category: 'admin',
    keywords: ['form', 'application', 'paperwork', 'fill', 'complete'],
    steps: [
      'Open the document or email',
      'Read just the first paragraph',
      'Fill in the first 3 fields',
      'Save and come back later if needed',
    ],
    difficulty: 'medium',
    estimatedTime: '15 min',
  },
  {
    id: 'schedule-appointment',
    title: 'Schedule an appointment',
    emoji: '📅',
    category: 'admin',
    keywords: ['appointment', 'schedule', 'book', 'doctor', 'meeting'],
    steps: [
      'Find the phone number or website',
      'Call or open the booking page',
      'Pick a date and time',
      'Confirm the appointment',
    ],
    difficulty: 'medium',
    estimatedTime: '10 min',
    linkedWidgetType: 'calendar',
    linkedWidgetLabel: 'Calendar',
  },
  {
    id: 'file-documents',
    title: 'File important documents',
    emoji: '📁',
    category: 'admin',
    keywords: ['file', 'documents', 'organize', 'paperwork', 'important'],
    steps: [
      'Gather 3-5 documents',
      'Put them in a folder or envelope',
      'Label it if helpful',
      'Put it somewhere safe',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'update-password',
    title: 'Update one password',
    emoji: '🔐',
    category: 'admin',
    keywords: ['password', 'security', 'update', 'account', 'login'],
    steps: [
      'Pick one account to update',
      'Go to account settings',
      'Change the password',
      'Save it somewhere safe',
    ],
    difficulty: 'medium',
    estimatedTime: '10 min',
  },
  {
    id: 'renew-subscription',
    title: 'Check subscription renewals',
    emoji: '💳',
    category: 'admin',
    keywords: ['subscription', 'renew', 'cancel', 'membership', 'service'],
    steps: [
      'Check your email or bank statement',
      'See what subscriptions you have',
      'Decide if you want to keep or cancel one',
      'Take action if needed',
    ],
    difficulty: 'medium',
    estimatedTime: '10 min',
  },
  {
    id: 'backup-phone',
    title: 'Back up phone photos',
    emoji: '📱',
    category: 'admin',
    keywords: ['backup', 'photos', 'phone', 'cloud', 'save'],
    steps: [
      'Open your photos app',
      'Check if auto-backup is on',
      'Or manually back up recent photos',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'update-address',
    title: 'Update address on one account',
    emoji: '📍',
    category: 'admin',
    keywords: ['address', 'update', 'account', 'profile', 'information'],
    steps: [
      'Pick one account that needs updating',
      'Go to account settings',
      'Update the address',
      'Save changes',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },

  // ============================================================================
  // HEALTH & HYGIENE
  // ============================================================================
  {
    id: 'shower',
    title: 'Take a shower',
    emoji: '🚿',
    category: 'hygiene',
    keywords: ['shower', 'wash', 'clean', 'bath', 'hygiene'],
    steps: [
      'Get your towel and clothes ready',
      'Turn on the water',
      'Get in and wash',
      'Dry off and get dressed',
    ],
    difficulty: 'easy',
    estimatedTime: '15 min',
  },
  {
    id: 'brush-teeth',
    title: 'Brush teeth',
    emoji: '🦷',
    category: 'hygiene',
    keywords: ['teeth', 'brush', 'dental', 'oral', 'hygiene'],
    steps: [
      'Get your toothbrush and toothpaste',
      'Brush for 2 minutes',
      'Rinse your mouth',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'wash-face',
    title: 'Wash your face',
    emoji: '🧼',
    category: 'hygiene',
    keywords: ['face', 'wash', 'skincare', 'clean', 'hygiene'],
    steps: [
      'Wet your face with warm water',
      'Use a gentle cleanser',
      'Rinse and pat dry',
      'Apply moisturizer if you have it',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'skincare-routine',
    title: 'Do a quick skincare routine',
    emoji: '✨',
    category: 'hygiene',
    keywords: ['skincare', 'routine', 'face', 'moisturize', 'care'],
    steps: [
      'Wash your face',
      'Apply moisturizer',
      'Add sunscreen if it\'s daytime',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'trim-nails',
    title: 'Trim your nails',
    emoji: '✂️',
    category: 'hygiene',
    keywords: ['nails', 'trim', 'groom', 'hygiene', 'care'],
    steps: [
      'Get nail clippers',
      'Trim one hand',
      'Trim the other hand',
      'File rough edges if needed',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'haircare',
    title: 'Wash or style your hair',
    emoji: '💇',
    category: 'hygiene',
    keywords: ['hair', 'wash', 'style', 'groom', 'care'],
    steps: [
      'Wet your hair',
      'Apply shampoo and rinse',
      'Condition if you want',
      'Style or let air dry',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'take-meds',
    title: 'Take medication',
    emoji: '💊',
    category: 'health',
    keywords: ['medication', 'medicine', 'pills', 'meds', 'prescription'],
    steps: [
      'Get your medication',
      'Check the label or reminder',
      'Take with water',
      'Mark it done if you track it',
    ],
    difficulty: 'easy',
    estimatedTime: '1 min',
  },
  {
    id: 'doctor-appointment',
    title: 'Schedule a doctor appointment',
    emoji: '🏥',
    category: 'health',
    keywords: ['doctor', 'appointment', 'health', 'checkup', 'medical'],
    steps: [
      'Find your doctor\'s phone number',
      'Call or book online',
      'Pick a date and time',
      'Add it to your calendar',
    ],
    difficulty: 'medium',
    estimatedTime: '10 min',
    linkedWidgetType: 'calendar',
    linkedWidgetLabel: 'Calendar',
  },
  {
    id: 'therapy-session',
    title: 'Schedule or prepare for therapy',
    emoji: '💚',
    category: 'health',
    keywords: ['therapy', 'counseling', 'mental health', 'support', 'session'],
    steps: [
      'Check your next appointment time',
      'Or schedule a new one',
      'Write down one thing to discuss',
      'That\'s enough preparation',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'calendar',
    linkedWidgetLabel: 'Calendar',
  },
  {
    id: 'check-symptoms',
    title: 'Track symptoms or mood',
    emoji: '📊',
    category: 'health',
    keywords: ['symptoms', 'track', 'mood', 'health', 'monitor'],
    steps: [
      'Get a notebook or app',
      'Write down how you feel today',
      'Note any symptoms if relevant',
      'You can review later',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'refill-prescription',
    title: 'Refill a prescription',
    emoji: '💊',
    category: 'health',
    keywords: ['prescription', 'refill', 'pharmacy', 'medication', 'pharmacy'],
    steps: [
      'Check if you need a refill',
      'Call pharmacy or use app',
      'Pick up when ready',
      'Or schedule delivery',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'eat-breakfast',
    title: 'Eat breakfast',
    emoji: '🥐',
    category: 'nutrition',
    keywords: ['breakfast', 'eat', 'morning', 'meal', 'food', 'start day'],
    steps: [
      'Decide what you want for breakfast',
      'Prepare or get the food',
      'Sit down and eat',
      'Notice when you feel full',
    ],
    difficulty: 'easy',
    estimatedTime: '15 min',
    linkedWidgetType: 'meal_planner',
    linkedWidgetLabel: 'Meal Planner',
  },
  {
    id: 'eat-lunch',
    title: 'Eat lunch',
    emoji: '🥪',
    category: 'nutrition',
    keywords: ['lunch', 'eat', 'midday', 'meal', 'food', 'noon'],
    steps: [
      'Decide what you want for lunch',
      'Prepare or get the food',
      'Sit down and eat',
      'Notice when you feel full',
    ],
    difficulty: 'easy',
    estimatedTime: '20 min',
    linkedWidgetType: 'meal_planner',
    linkedWidgetLabel: 'Meal Planner',
  },
  {
    id: 'eat-dinner',
    title: 'Eat dinner',
    emoji: '🍽️',
    category: 'nutrition',
    keywords: ['dinner', 'eat', 'evening', 'meal', 'food', 'supper'],
    steps: [
      'Decide what you want for dinner',
      'Prepare or get the food',
      'Sit down and eat',
      'Notice when you feel full',
    ],
    difficulty: 'easy',
    estimatedTime: '25 min',
    linkedWidgetType: 'meal_planner',
    linkedWidgetLabel: 'Meal Planner',
  },
  {
    id: 'eat-snack',
    title: 'Eat a snack',
    emoji: '🍎',
    category: 'nutrition',
    keywords: ['snack', 'eat', 'food', 'healthy', 'quick', 'between meals'],
    steps: [
      'Choose something simple',
      'Get it from the fridge or pantry',
      'Sit down if you can',
      'Enjoy it',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'prepare-snack',
    title: 'Prepare a healthy snack',
    emoji: '🥗',
    category: 'nutrition',
    keywords: ['snack', 'food', 'prepare', 'healthy', 'cut', 'plate'],
    steps: [
      'Choose something simple',
      'Get it from the fridge or pantry',
      'Put it on a plate or in a bowl',
      'Enjoy it',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'plan-meals',
    title: 'Plan meals for tomorrow',
    emoji: '🍳',
    category: 'nutrition',
    keywords: ['meal plan', 'plan', 'meals', 'food', 'prep'],
    steps: [
      'Think of 2-3 meals for tomorrow',
      'Write them down or remember them',
      'Check if you have ingredients',
      'Add missing items to grocery list',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'meal_planner',
    linkedWidgetLabel: 'Meal Planner',
  },
  {
    id: 'meal-prep',
    title: 'Prep one meal component',
    emoji: '🥗',
    category: 'nutrition',
    keywords: ['meal prep', 'prepare', 'cook', 'food', 'prep'],
    steps: [
      'Pick one thing to prep (veggies, grains, etc.)',
      'Wash and cut if needed',
      'Store in container',
      'You can do more later',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
    linkedWidgetType: 'meal_planner',
    linkedWidgetLabel: 'Meal Planner',
  },
  {
    id: 'grocery-shop',
    title: 'Go grocery shopping',
    emoji: '🛒',
    category: 'nutrition',
    keywords: ['grocery', 'shop', 'shopping', 'store', 'food'],
    steps: [
      'Get your grocery list',
      'Go to the store',
      'Get the items on your list',
      'Check out and come home',
    ],
    difficulty: 'medium',
    estimatedTime: '30 min',
    linkedWidgetType: 'grocery_list',
    linkedWidgetLabel: 'Grocery List',
  },
  {
    id: 'cook-simple-meal',
    title: 'Cook a simple meal',
    emoji: '🍲',
    category: 'nutrition',
    keywords: ['cook', 'meal', 'food', 'prepare', 'kitchen'],
    steps: [
      'Pick something simple to make',
      'Get the ingredients',
      'Follow the recipe or your memory',
      'Enjoy your meal',
    ],
    difficulty: 'medium',
    estimatedTime: '30 min',
    linkedWidgetType: 'meal_planner',
    linkedWidgetLabel: 'Meal Planner',
  },

  // ============================================================================
  // MOVEMENT & EXERCISE
  // ============================================================================
  {
    id: 'walk',
    title: 'Go for a short walk',
    emoji: '🚶',
    category: 'movement',
    keywords: ['walk', 'exercise', 'movement', 'outside', 'fresh air'],
    steps: [
      'Put on shoes',
      'Step outside',
      'Walk for 5 minutes',
      'Come back inside',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'exercise',
    title: 'Do 10 minutes of exercise',
    emoji: '💪',
    category: 'movement',
    keywords: ['exercise', 'workout', 'fitness', 'move', 'active'],
    steps: [
      'Put on comfortable clothes',
      'Choose 3 simple exercises',
      'Do each for 2-3 minutes',
      'Stretch when done',
    ],
    difficulty: 'medium',
    estimatedTime: '15 min',
  },
  {
    id: 'dance',
    title: 'Dance to one song',
    emoji: '💃',
    category: 'movement',
    keywords: ['dance', 'music', 'move', 'fun', 'energy'],
    steps: [
      'Put on a song you love',
      'Stand up',
      'Move your body however feels good',
      'Enjoy the moment',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'yoga',
    title: 'Do 10 minutes of yoga',
    emoji: '🧘',
    category: 'movement',
    keywords: ['yoga', 'stretch', 'flexibility', 'movement', 'exercise'],
    steps: [
      'Find a quiet space',
      'Do 3-5 simple poses',
      'Hold each for 30 seconds',
      'Finish with a moment of calm',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'stair-climb',
    title: 'Climb stairs 3 times',
    emoji: '🪜',
    category: 'movement',
    keywords: ['stairs', 'climb', 'exercise', 'movement', 'cardio'],
    steps: [
      'Find a set of stairs',
      'Walk up and down once',
      'Repeat two more times',
      'Take a break when done',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'parking-lot-walk',
    title: 'Park farther away and walk',
    emoji: '🚗',
    category: 'movement',
    keywords: ['walk', 'parking', 'movement', 'exercise', 'steps'],
    steps: [
      'When you arrive somewhere',
      'Park in a spot farther away',
      'Walk to your destination',
      'Every step counts!',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'stretch-routine',
    title: 'Do a full body stretch',
    emoji: '🤸',
    category: 'movement',
    keywords: ['stretch', 'flexibility', 'body', 'movement', 'warm up'],
    steps: [
      'Stand or sit comfortably',
      'Stretch arms up and hold',
      'Stretch legs and hold',
      'Roll shoulders and neck',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },

  // ============================================================================
  // PLANNING & ORGANIZATION
  // ============================================================================
  {
    id: 'check-plan',
    title: 'Check today\'s plan',
    emoji: '🗓️',
    category: 'planning',
    keywords: ['plan', 'today', 'schedule', 'calendar', 'check'],
    steps: [
      'Open your planner or calendar',
      'Look at what\'s scheduled',
      'Pick one thing to focus on',
      'That\'s it - no pressure to do it all',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
    linkedWidgetType: 'calendar',
    linkedWidgetLabel: 'Calendar',
  },
  {
    id: 'organize-drawer',
    title: 'Organize one drawer',
    emoji: '📦',
    category: 'organization',
    keywords: ['organize', 'drawer', 'sort', 'tidy', 'arrange'],
    steps: [
      'Pick one drawer',
      'Take out 5 items',
      'Put away 3 items',
      'Put the rest back',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'declutter',
    title: 'Declutter a small area',
    emoji: '🗂️',
    category: 'organization',
    keywords: ['declutter', 'organize', 'sort', 'tidy', 'clear'],
    steps: [
      'Pick one small area',
      'Take out 5 items',
      'Put away 3 items',
      'Notice the difference',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'organize-email',
    title: 'Organize email inbox',
    emoji: '📧',
    category: 'organization',
    keywords: ['email', 'inbox', 'organize', 'sort', 'clean'],
    steps: [
      'Open your email',
      'Delete 5 old emails',
      'Archive 3 important ones',
      'You can do more later',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'organize-files',
    title: 'Organize computer files',
    emoji: '💻',
    category: 'organization',
    keywords: ['files', 'organize', 'computer', 'folders', 'digital'],
    steps: [
      'Open your documents folder',
      'Create 2-3 folders if needed',
      'Move 5 files to the right folders',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'organize-photos',
    title: 'Organize phone photos',
    emoji: '📸',
    category: 'organization',
    keywords: ['photos', 'organize', 'delete', 'album', 'pictures'],
    steps: [
      'Open your photos app',
      'Delete 5 blurry or duplicate photos',
      'Create one album if you want',
      'That\'s enough for now',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'label-containers',
    title: 'Label storage containers',
    emoji: '🏷️',
    category: 'organization',
    keywords: ['label', 'organize', 'storage', 'containers', 'identify'],
    steps: [
      'Get some labels or tape',
      'Pick 2-3 containers to label',
      'Write what\'s inside',
      'Stick the labels on',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'make-list',
    title: 'Make a simple list',
    emoji: '📝',
    category: 'planning',
    keywords: ['list', 'write', 'plan', 'organize', 'notes'],
    steps: [
      'Get paper or open notes app',
      'Write down 3 things on your mind',
      'You don\'t have to do them',
      'Just getting them out helps',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
    linkedWidgetType: 'note',
    linkedWidgetLabel: 'Notes',
  },
  {
    id: 'weekly-review',
    title: 'Do a quick weekly review',
    emoji: '📋',
    category: 'planning',
    keywords: ['review', 'week', 'reflect', 'plan', 'organize'],
    steps: [
      'Look at what you did this week',
      'Write down 3 things that went well',
      'Note one thing to improve',
      'That\'s enough reflection',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'time-block',
    title: 'Block time for one task',
    emoji: '⏰',
    category: 'planning',
    keywords: ['time block', 'schedule', 'plan', 'calendar', 'time'],
    steps: [
      'Pick one task you need to do',
      'Decide when you\'ll do it',
      'Add it to your calendar',
      'Set a reminder if helpful',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
    linkedWidgetType: 'calendar',
    linkedWidgetLabel: 'Calendar',
  },
  {
    id: 'set-goal',
    title: 'Set one small goal',
    emoji: '🎯',
    category: 'planning',
    keywords: ['goal', 'target', 'plan', 'objective', 'aim'],
    steps: [
      'Think of one small thing you want to do',
      'Write it down',
      'Break it into 2-3 steps',
      'Pick when you\'ll start',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'plan-tomorrow',
    title: 'Plan tomorrow\'s top 3 tasks',
    emoji: '📅',
    category: 'planning',
    keywords: ['plan', 'tomorrow', 'tasks', 'schedule', 'prepare'],
    steps: [
      'Write down 3 things for tomorrow',
      'Put them in order of importance',
      'Add to calendar if needed',
      'Done - you\'re prepared',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'calendar',
    linkedWidgetLabel: 'Calendar',
  },

  // ============================================================================
  // SOCIAL & COMMUNICATION
  // ============================================================================
  {
    id: 'text-friend',
    title: 'Text a friend',
    emoji: '💬',
    category: 'social',
    keywords: ['text', 'message', 'friend', 'contact', 'reach out'],
    steps: [
      'Open your messages',
      'Pick one person',
      'Write a short, friendly message',
      'Send it',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'plan-hangout',
    title: 'Plan a hangout with someone',
    emoji: '☕',
    category: 'social',
    keywords: ['hangout', 'social', 'friend', 'plan', 'meet'],
    steps: [
      'Think of someone you want to see',
      'Send them a message',
      'Suggest a time and place',
      'Wait for their response',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'send-card',
    title: 'Send a card or letter',
    emoji: '💌',
    category: 'social',
    keywords: ['card', 'letter', 'send', 'mail', 'thoughtful'],
    steps: [
      'Get a card or paper',
      'Write a short note',
      'Address the envelope',
      'Mail it or deliver it',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'reach-out-old-friend',
    title: 'Reach out to an old friend',
    emoji: '👋',
    category: 'social',
    keywords: ['friend', 'reach out', 'contact', 'reconnect', 'social'],
    steps: [
      'Think of someone you haven\'t talked to',
      'Send them a friendly message',
      'Ask how they\'re doing',
      'See where the conversation goes',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'call-someone',
    title: 'Call someone',
    emoji: '📞',
    category: 'social',
    keywords: ['call', 'phone', 'talk', 'contact', 'reach out'],
    steps: [
      'Pick someone you want to talk to',
      'Dial the number',
      'Have a short conversation',
      'Hang up when you\'re ready',
    ],
    difficulty: 'medium',
    estimatedTime: '15 min',
  },
  {
    id: 'reply-message',
    title: 'Reply to a message',
    emoji: '💭',
    category: 'communication',
    keywords: ['reply', 'message', 'respond', 'answer', 'text'],
    steps: [
      'Open your messages',
      'Find one you need to reply to',
      'Write a short response',
      'Send it',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'difficult-conversation',
    title: 'Prepare for a difficult conversation',
    emoji: '💬',
    category: 'communication',
    keywords: ['conversation', 'difficult', 'talk', 'communicate', 'discuss'],
    steps: [
      'Write down what you want to say',
      'Practice saying it out loud',
      'Think about when to have the talk',
      'You can do it when you\'re ready',
    ],
    difficulty: 'medium',
    estimatedTime: '10 min',
  },
  {
    id: 'send-thank-you',
    title: 'Send a thank you message',
    emoji: '💌',
    category: 'communication',
    keywords: ['thank you', 'gratitude', 'message', 'appreciation', 'send'],
    steps: [
      'Think of someone to thank',
      'Write a short message',
      'Send it via text or email',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'check-social-media',
    title: 'Check social media mindfully',
    emoji: '📱',
    category: 'communication',
    keywords: ['social media', 'check', 'connect', 'online', 'mindful'],
    steps: [
      'Set a timer for 5 minutes',
      'Check your notifications',
      'Reply to one message if you want',
      'Close the app when timer goes off',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },

  // ============================================================================
  // CREATIVE & LEARNING
  // ============================================================================
  {
    id: 'read',
    title: 'Read for 10 minutes',
    emoji: '📚',
    category: 'learning',
    keywords: ['read', 'book', 'article', 'learning', 'study'],
    steps: [
      'Pick something to read',
      'Set a timer for 10 minutes',
      'Read at your own pace',
      'Stop when the timer goes off',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'write',
    title: 'Write for 5 minutes',
    emoji: '✍️',
    category: 'creative',
    keywords: ['write', 'journal', 'creative', 'notes', 'thoughts'],
    steps: [
      'Get paper or open a document',
      'Set a timer for 5 minutes',
      'Write whatever comes to mind',
      'Stop when the timer goes off',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'workspace',
    linkedWidgetLabel: 'Workspace',
  },
  {
    id: 'draw',
    title: 'Draw or doodle',
    emoji: '🎨',
    category: 'creative',
    keywords: ['draw', 'doodle', 'art', 'creative', 'sketch'],
    steps: [
      'Get paper and pen or pencil',
      'Draw whatever you feel like',
      'No pressure to make it perfect',
      'Enjoy the process',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'listen-music',
    title: 'Listen to music mindfully',
    emoji: '🎵',
    category: 'creative',
    keywords: ['music', 'listen', 'enjoy', 'creative', 'relax'],
    steps: [
      'Pick a song or album',
      'Put on headphones if you want',
      'Listen and notice how it makes you feel',
      'Enjoy the moment',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'craft-project',
    title: 'Work on a craft project',
    emoji: '✂️',
    category: 'creative',
    keywords: ['craft', 'creative', 'make', 'project', 'art'],
    steps: [
      'Pick a simple craft project',
      'Gather materials',
      'Work on it for 15 minutes',
      'You can continue later',
    ],
    difficulty: 'medium',
    estimatedTime: '15 min',
  },
  {
    id: 'take-photo',
    title: 'Take a photo of something',
    emoji: '📷',
    category: 'creative',
    keywords: ['photo', 'photography', 'picture', 'capture', 'creative'],
    steps: [
      'Look around for something interesting',
      'Take a photo with your phone',
      'Or use a camera if you have one',
      'Save it or share it',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'cook-creative',
    title: 'Cook something creative',
    emoji: '👨‍🍳',
    category: 'creative',
    keywords: ['cook', 'creative', 'recipe', 'food', 'kitchen'],
    steps: [
      'Pick a recipe you want to try',
      'Gather ingredients',
      'Follow the recipe',
      'Enjoy what you made',
    ],
    difficulty: 'medium',
    estimatedTime: '30 min',
    linkedWidgetType: 'meal_planner',
    linkedWidgetLabel: 'Meal Planner',
  },
  {
    id: 'learn-something',
    title: 'Learn something new',
    emoji: '🧠',
    category: 'learning',
    keywords: ['learn', 'study', 'education', 'skill', 'knowledge'],
    steps: [
      'Pick a topic you\'re curious about',
      'Watch a 5-minute video or read an article',
      'Take one note if you want',
      'That\'s enough for now',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'watch-tutorial',
    title: 'Watch a tutorial',
    emoji: '🎥',
    category: 'learning',
    keywords: ['tutorial', 'video', 'learn', 'how to', 'instruction'],
    steps: [
      'Pick something you want to learn',
      'Find a 5-10 minute tutorial',
      'Watch it and follow along',
      'Try it yourself if you want',
    ],
    difficulty: 'easy',
    estimatedTime: '15 min',
  },
  {
    id: 'take-notes',
    title: 'Take notes on something',
    emoji: '📝',
    category: 'learning',
    keywords: ['notes', 'write', 'learn', 'study', 'remember'],
    steps: [
      'Pick something you want to remember',
      'Get paper or open notes',
      'Write down 3 key points',
      'You can review later',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'note',
    linkedWidgetLabel: 'Notes',
  },
  {
    id: 'practice-skill',
    title: 'Practice a skill for 10 minutes',
    emoji: '🎯',
    category: 'learning',
    keywords: ['practice', 'skill', 'improve', 'learn', 'develop'],
    steps: [
      'Pick one skill to practice',
      'Set a timer for 10 minutes',
      'Practice until timer goes off',
      'Notice your progress',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'read-article',
    title: 'Read an article',
    emoji: '📰',
    category: 'learning',
    keywords: ['read', 'article', 'news', 'learn', 'information'],
    steps: [
      'Find an interesting article',
      'Read it at your own pace',
      'Take one note if helpful',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },

  // ============================================================================
  // MINDFULNESS & MENTAL HEALTH
  // ============================================================================
  {
    id: 'meditate',
    title: 'Meditate for 3 minutes',
    emoji: '🧘',
    category: 'mindfulness',
    keywords: ['meditate', 'meditation', 'mindful', 'calm', 'peace'],
    steps: [
      'Find a quiet spot',
      'Sit comfortably',
      'Close your eyes or soften your gaze',
      'Focus on your breath for 3 minutes',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'journal',
    title: 'Write in journal',
    emoji: '📔',
    category: 'mindfulness',
    keywords: ['journal', 'write', 'reflect', 'thoughts', 'feelings'],
    steps: [
      'Get your journal or open notes',
      'Write 3 sentences about how you feel',
      'Or write about one thing that happened',
      'Close it when you\'re done',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'journal',
    linkedWidgetLabel: 'Journal',
  },
  {
    id: 'nature-break',
    title: 'Spend 5 minutes in nature',
    emoji: '🌳',
    category: 'mindfulness',
    keywords: ['nature', 'outside', 'fresh air', 'park', 'garden'],
    steps: [
      'Step outside or look out a window',
      'Notice 3 things you see',
      'Take a few deep breaths',
      'Come back inside when ready',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'body-scan',
    title: 'Do a quick body scan',
    emoji: '🧘',
    category: 'mindfulness',
    keywords: ['body scan', 'mindful', 'awareness', 'relax', 'check in'],
    steps: [
      'Sit or lie comfortably',
      'Notice your feet and legs',
      'Notice your torso and arms',
      'Notice your head and face',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'gratitude-practice',
    title: 'Write 3 things you\'re grateful for',
    emoji: '🙏',
    category: 'mindfulness',
    keywords: ['gratitude', 'thankful', 'appreciate', 'write', 'positive'],
    steps: [
      'Get paper or open notes',
      'Write down 3 things you\'re grateful for',
      'They can be big or small',
      'Read them back to yourself',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
    linkedWidgetType: 'journal',
    linkedWidgetLabel: 'Journal',
  },
  {
    id: 'reflection',
    title: 'Reflect on your day',
    emoji: '🤔',
    category: 'mindfulness',
    keywords: ['reflect', 'think', 'review', 'mindful', 'day'],
    steps: [
      'Think about your day',
      'What went well?',
      'What was challenging?',
      'Write it down if helpful',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'journal',
    linkedWidgetLabel: 'Journal',
  },
  {
    id: 'mindful-eating',
    title: 'Eat one thing mindfully',
    emoji: '🍎',
    category: 'mindfulness',
    keywords: ['mindful', 'eating', 'food', 'awareness', 'present'],
    steps: [
      'Pick one food item',
      'Notice how it looks',
      'Take a bite and notice the taste',
      'Chew slowly and enjoy',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },

  // ============================================================================
  // MAINTENANCE & ERRANDS
  // ============================================================================
  {
    id: 'grocery-list',
    title: 'Make a grocery list',
    emoji: '🛒',
    category: 'planning',
    keywords: ['grocery', 'shopping', 'list', 'food', 'store'],
    steps: [
      'Get paper or open notes',
      'Write down 5 things you need',
      'You can add more later',
      'That\'s enough for now',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
    linkedWidgetType: 'grocery_list',
    linkedWidgetLabel: 'Grocery List',
  },
  {
    id: 'change-sheets',
    title: 'Change bed sheets',
    emoji: '🛏️',
    category: 'maintenance',
    keywords: ['sheets', 'bed', 'change', 'linen', 'bedroom'],
    steps: [
      'Take off the old sheets',
      'Put on the bottom sheet',
      'Put on the top sheet',
      'Fluff the pillow',
    ],
    difficulty: 'medium',
    estimatedTime: '10 min',
  },
  {
    id: 'water-plants',
    title: 'Water plants',
    emoji: '🌱',
    category: 'maintenance',
    keywords: ['plants', 'water', 'garden', 'care', 'nature'],
    steps: [
      'Check which plants need water',
      'Water 2-3 plants',
      'You can do more later',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'car-maintenance',
    title: 'Check car maintenance',
    emoji: '🚗',
    category: 'maintenance',
    keywords: ['car', 'vehicle', 'maintenance', 'check', 'oil'],
    steps: [
      'Check your car\'s mileage',
      'See if oil change is due',
      'Check tire pressure',
      'Schedule service if needed',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'home-repair',
    title: 'Fix one small thing at home',
    emoji: '🔧',
    category: 'maintenance',
    keywords: ['repair', 'fix', 'home', 'maintenance', 'broken'],
    steps: [
      'Identify one small thing to fix',
      'Get the tools you need',
      'Fix it or schedule a repair',
      'Done!',
    ],
    difficulty: 'medium',
    estimatedTime: '15 min',
  },
  {
    id: 'tech-update',
    title: 'Update apps or software',
    emoji: '💻',
    category: 'maintenance',
    keywords: ['update', 'apps', 'software', 'tech', 'phone'],
    steps: [
      'Check for app updates',
      'Update 2-3 apps',
      'Or update your phone/computer',
      'Restart if needed',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'check-batteries',
    title: 'Check and replace batteries',
    emoji: '🔋',
    category: 'maintenance',
    keywords: ['batteries', 'replace', 'check', 'smoke detector', 'devices'],
    steps: [
      'Check smoke detector batteries',
      'Or check remote control batteries',
      'Replace if needed',
      'Test to make sure they work',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'organize-cables',
    title: 'Organize cables and cords',
    emoji: '🔌',
    category: 'maintenance',
    keywords: ['cables', 'cords', 'organize', 'tidy', 'electronics'],
    steps: [
      'Gather loose cables',
      'Untangle them',
      'Roll them up or use ties',
      'Store in one place',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'backup-photos',
    title: 'Backup phone photos',
    emoji: '📱',
    category: 'maintenance',
    keywords: ['backup', 'photos', 'cloud', 'save', 'phone', 'pictures'],
    steps: [
      'Open your photo app',
      'Select a few photos to backup',
      'Upload to cloud or computer',
      'You can do more later',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'clean-out-fridge',
    title: 'Clean out fridge',
    emoji: '🧹',
    category: 'cleaning',
    keywords: ['fridge', 'refrigerator', 'clean', 'expired', 'food'],
    steps: [
      'Check expiration dates',
      'Remove 2-3 expired items',
      'Wipe one shelf',
      'You can do more later',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'sort-laundry',
    title: 'Sort laundry',
    emoji: '👕',
    category: 'cleaning',
    keywords: ['laundry', 'sort', 'clothes', 'wash', 'organize'],
    steps: [
      'Gather dirty clothes',
      'Sort into 2 piles (lights and darks)',
      'Put one pile in the hamper',
      'You can wash later',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'fold-laundry',
    title: 'Fold one load of laundry',
    emoji: '👔',
    category: 'cleaning',
    keywords: ['fold', 'laundry', 'clothes', 'put away', 'organize'],
    steps: [
      'Get one load of clean laundry',
      'Fold 5 items',
      'Put them away',
      'You can do more later',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'wipe-surfaces',
    title: 'Wipe down kitchen surfaces',
    emoji: '🧽',
    category: 'cleaning',
    keywords: ['wipe', 'kitchen', 'surfaces', 'counter', 'clean'],
    steps: [
      'Get a cloth or sponge',
      'Wipe the counter',
      'Wipe the stove',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'empty-trash',
    title: 'Empty trash cans',
    emoji: '🗑️',
    category: 'cleaning',
    keywords: ['trash', 'garbage', 'empty', 'bin', 'dispose'],
    steps: [
      'Check kitchen trash',
      'Take out if full',
      'Put in a new bag',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'vacuum-one-room',
    title: 'Vacuum one room',
    emoji: '🧹',
    category: 'cleaning',
    keywords: ['vacuum', 'clean', 'floor', 'room', 'carpet'],
    steps: [
      'Get the vacuum',
      'Vacuum one room',
      'Put vacuum away',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'clean-bathroom-mirror',
    title: 'Clean bathroom mirror',
    emoji: '🪞',
    category: 'cleaning',
    keywords: ['mirror', 'bathroom', 'clean', 'wipe', 'glass'],
    steps: [
      'Get glass cleaner or water',
      'Spray or wet the mirror',
      'Wipe with a cloth',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'organize-drawer',
    title: 'Organize one drawer',
    emoji: '📦',
    category: 'organization',
    keywords: ['drawer', 'organize', 'tidy', 'sort', 'declutter'],
    steps: [
      'Pick one drawer',
      'Take everything out',
      'Put back what you need',
      'Throw away what you don\'t',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'sort-papers',
    title: 'Sort papers and mail',
    emoji: '📄',
    category: 'organization',
    keywords: ['papers', 'mail', 'sort', 'organize', 'file'],
    steps: [
      'Gather papers in one place',
      'Sort into 3 piles: keep, recycle, action',
      'Recycle what you don\'t need',
      'Put keep pile in a folder',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'clean-out-purse',
    title: 'Clean out purse or wallet',
    emoji: '👛',
    category: 'organization',
    keywords: ['purse', 'wallet', 'clean', 'organize', 'declutter'],
    steps: [
      'Empty everything out',
      'Throw away trash',
      'Put back what you need',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'organize-shoes',
    title: 'Organize shoes',
    emoji: '👟',
    category: 'organization',
    keywords: ['shoes', 'organize', 'tidy', 'closet', 'entryway'],
    steps: [
      'Gather shoes in one place',
      'Pair them up',
      'Put them where they belong',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'make-to-do-list',
    title: 'Make a to-do list',
    emoji: '📝',
    category: 'planning',
    keywords: ['list', 'plan', 'tasks', 'organize', 'prioritize'],
    steps: [
      'Get paper or open notes',
      'Write down 3-5 things to do',
      'Pick one to start with',
      'You can add more later',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'review-calendar',
    title: 'Review calendar for the week',
    emoji: '📅',
    category: 'planning',
    keywords: ['calendar', 'review', 'plan', 'schedule', 'week'],
    steps: [
      'Open your calendar',
      'Look at this week',
      'Note any important dates',
      'Add reminders if needed',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'calendar',
    linkedWidgetLabel: 'Calendar',
  },
  {
    id: 'set-reminders',
    title: 'Set reminders for tomorrow',
    emoji: '⏰',
    category: 'planning',
    keywords: ['reminders', 'alarms', 'schedule', 'plan', 'remember'],
    steps: [
      'Think of 2-3 things to remember',
      'Set phone reminders',
      'Or write them down',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'plan-weekend',
    title: 'Plan one thing for the weekend',
    emoji: '🎉',
    category: 'planning',
    keywords: ['weekend', 'plan', 'fun', 'activity', 'schedule'],
    steps: [
      'Think of one thing you\'d like to do',
      'Check if you need to book anything',
      'Add it to your calendar',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'check-email',
    title: 'Check and respond to emails',
    emoji: '📧',
    category: 'communication',
    keywords: ['email', 'check', 'respond', 'messages', 'inbox'],
    steps: [
      'Open your email',
      'Read 3-5 new emails',
      'Respond to 1-2 if needed',
      'You can do more later',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'text-friend',
    title: 'Text or call a friend',
    emoji: '💬',
    category: 'social',
    keywords: ['text', 'call', 'friend', 'social', 'connect'],
    steps: [
      'Think of someone you want to reach out to',
      'Send a quick text or call',
      'Ask how they\'re doing',
      'Enjoy the connection',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'reply-messages',
    title: 'Reply to messages',
    emoji: '💭',
    category: 'communication',
    keywords: ['messages', 'reply', 'text', 'respond', 'chat'],
    steps: [
      'Open your messages',
      'Read unread messages',
      'Reply to 2-3 people',
      'You can do more later',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'make-appointment',
    title: 'Make an appointment',
    emoji: '📞',
    category: 'health',
    keywords: ['appointment', 'doctor', 'schedule', 'call', 'book'],
    steps: [
      'Decide what appointment you need',
      'Find the phone number',
      'Call and schedule',
      'Add to your calendar',
    ],
    difficulty: 'medium',
    estimatedTime: '10 min',
  },
  {
    id: 'take-vitamins',
    title: 'Take vitamins or medication',
    emoji: '💊',
    category: 'health',
    keywords: ['vitamins', 'medication', 'medicine', 'health', 'pills'],
    steps: [
      'Get your vitamins or medication',
      'Take them with water',
      'Check if you need to refill',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '1 min',
  },
  {
    id: 'check-blood-pressure',
    title: 'Check blood pressure',
    emoji: '🩺',
    category: 'health',
    keywords: ['blood pressure', 'health', 'check', 'monitor', 'vitals'],
    steps: [
      'Get your blood pressure monitor',
      'Sit quietly for 2 minutes',
      'Take your reading',
      'Record it if needed',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'stretch-neck',
    title: 'Do neck stretches',
    emoji: '🦴',
    category: 'health',
    keywords: ['stretch', 'neck', 'tension', 'pain', 'relief'],
    steps: [
      'Sit or stand comfortably',
      'Slowly tilt head to one side',
      'Hold for 10 seconds',
      'Repeat on other side',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'eye-exercises',
    title: 'Do eye exercises',
    emoji: '👁️',
    category: 'health',
    keywords: ['eyes', 'exercise', 'rest', 'screen time', 'vision'],
    steps: [
      'Look away from your screen',
      'Focus on something far away',
      'Blink 10 times',
      'Look left and right slowly',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'drink-tea',
    title: 'Make and drink tea',
    emoji: '☕',
    category: 'self-care',
    keywords: ['tea', 'drink', 'warm', 'relax', 'comfort'],
    steps: [
      'Boil water or heat in microwave',
      'Steep your tea',
      'Sit down and enjoy',
      'Take a moment to relax',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'apply-lotion',
    title: 'Apply lotion or moisturizer',
    emoji: '🧴',
    category: 'hygiene',
    keywords: ['lotion', 'moisturizer', 'skin', 'care', 'hydrate'],
    steps: [
      'Get your lotion',
      'Apply to hands and arms',
      'Or apply to face',
      'Feel the comfort',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'brush-teeth',
    title: 'Brush teeth',
    emoji: '🪥',
    category: 'hygiene',
    keywords: ['teeth', 'brush', 'hygiene', 'oral', 'clean'],
    steps: [
      'Get your toothbrush and toothpaste',
      'Brush for 2 minutes',
      'Rinse your mouth',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'wash-face',
    title: 'Wash face',
    emoji: '💧',
    category: 'hygiene',
    keywords: ['face', 'wash', 'clean', 'skin', 'fresh'],
    steps: [
      'Wet your face with water',
      'Use a gentle cleanser',
      'Rinse with water',
      'Pat dry',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'take-shower',
    title: 'Take a shower',
    emoji: '🚿',
    category: 'hygiene',
    keywords: ['shower', 'wash', 'clean', 'bath', 'fresh'],
    steps: [
      'Get your towel and clothes ready',
      'Get in the shower',
      'Wash your body and hair',
      'Get out and dry off',
    ],
    difficulty: 'easy',
    estimatedTime: '15 min',
  },
  {
    id: 'do-hair',
    title: 'Do your hair',
    emoji: '💇',
    category: 'hygiene',
    keywords: ['hair', 'style', 'brush', 'groom', 'care'],
    steps: [
      'Brush or comb your hair',
      'Style it how you like',
      'Or just make it neat',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'trim-nails',
    title: 'Trim nails',
    emoji: '✂️',
    category: 'hygiene',
    keywords: ['nails', 'trim', 'cut', 'groom', 'care'],
    steps: [
      'Get nail clippers',
      'Trim fingernails or toenails',
      'File if needed',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'dance-move',
    title: 'Dance to one song',
    emoji: '💃',
    category: 'movement',
    keywords: ['dance', 'move', 'music', 'fun', 'exercise'],
    steps: [
      'Pick a song you love',
      'Turn it on',
      'Move your body',
      'Enjoy the moment',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'jumping-jacks',
    title: 'Do 10 jumping jacks',
    emoji: '🤸',
    category: 'movement',
    keywords: ['jumping jacks', 'exercise', 'cardio', 'movement', 'quick'],
    steps: [
      'Stand with feet together',
      'Jump and spread legs',
      'Raise arms overhead',
      'Jump back to start',
    ],
    difficulty: 'easy',
    estimatedTime: '1 min',
  },
  {
    id: 'squats',
    title: 'Do 5 squats',
    emoji: '🏋️',
    category: 'movement',
    keywords: ['squats', 'exercise', 'legs', 'strength', 'movement'],
    steps: [
      'Stand with feet shoulder-width apart',
      'Lower down like sitting in a chair',
      'Stand back up',
      'Repeat 4 more times',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'push-ups',
    title: 'Do 5 push-ups',
    emoji: '💪',
    category: 'movement',
    keywords: ['push-ups', 'exercise', 'arms', 'strength', 'movement'],
    steps: [
      'Get in push-up position',
      'Lower your body down',
      'Push back up',
      'Repeat 4 more times',
    ],
    difficulty: 'medium',
    estimatedTime: '2 min',
  },
  {
    id: 'yoga-pose',
    title: 'Do one yoga pose',
    emoji: '🧘',
    category: 'movement',
    keywords: ['yoga', 'pose', 'stretch', 'flexibility', 'calm'],
    steps: [
      'Find a comfortable spot',
      'Pick a simple pose',
      'Hold for 30 seconds',
      'Breathe deeply',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'stair-climb',
    title: 'Climb stairs 3 times',
    emoji: '🪜',
    category: 'movement',
    keywords: ['stairs', 'climb', 'exercise', 'cardio', 'movement'],
    steps: [
      'Find a set of stairs',
      'Walk up and down',
      'Repeat 2 more times',
      'Take a break',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'listen-podcast',
    title: 'Listen to a podcast',
    emoji: '🎧',
    category: 'learning',
    keywords: ['podcast', 'listen', 'learn', 'audio', 'entertainment'],
    steps: [
      'Pick a podcast episode',
      'Put on headphones',
      'Listen for 10 minutes',
      'You can continue later',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'watch-tutorial',
    title: 'Watch a tutorial video',
    emoji: '📺',
    category: 'learning',
    keywords: ['tutorial', 'video', 'learn', 'youtube', 'skill'],
    steps: [
      'Pick something you want to learn',
      'Find a 5-10 minute video',
      'Watch and take notes',
      'Try it yourself if you want',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'practice-language',
    title: 'Practice a language',
    emoji: '🗣️',
    category: 'learning',
    keywords: ['language', 'practice', 'learn', 'speak', 'foreign'],
    steps: [
      'Open a language app or website',
      'Do one lesson',
      'Or practice speaking for 5 minutes',
      'Done!',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'read-article',
    title: 'Read an article',
    emoji: '📰',
    category: 'learning',
    keywords: ['article', 'read', 'news', 'learn', 'information'],
    steps: [
      'Pick an article to read',
      'Read for 5-10 minutes',
      'Take notes if helpful',
      'You can finish later',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'color-page',
    title: 'Color a coloring page',
    emoji: '🎨',
    category: 'creative',
    keywords: ['color', 'coloring', 'relax', 'creative', 'art'],
    steps: [
      'Get a coloring book or print a page',
      'Pick your colors',
      'Color for 10 minutes',
      'Enjoy the process',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'write-poem',
    title: 'Write a short poem',
    emoji: '✍️',
    category: 'creative',
    keywords: ['poem', 'write', 'creative', 'poetry', 'express'],
    steps: [
      'Get paper or open a document',
      'Write 4-8 lines',
      'Don\'t worry about perfection',
      'Enjoy expressing yourself',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'sing-song',
    title: 'Sing a song',
    emoji: '🎤',
    category: 'creative',
    keywords: ['sing', 'song', 'music', 'voice', 'express'],
    steps: [
      'Pick a song you love',
      'Sing along or sing it yourself',
      'Enjoy the music',
      'Feel the joy',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'play-instrument',
    title: 'Play an instrument',
    emoji: '🎹',
    category: 'creative',
    keywords: ['instrument', 'music', 'play', 'piano', 'guitar'],
    steps: [
      'Get your instrument',
      'Play for 5-10 minutes',
      'Practice a song or improvise',
      'Enjoy the music',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'gratitude-list',
    title: 'Write 3 things you\'re grateful for',
    emoji: '🙏',
    category: 'mindfulness',
    keywords: ['gratitude', 'thankful', 'appreciate', 'positive', 'list'],
    steps: [
      'Get paper or open notes',
      'Write down 3 things',
      'They can be big or small',
      'Notice how you feel',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'progressive-relaxation',
    title: 'Do progressive muscle relaxation',
    emoji: '🧘',
    category: 'mindfulness',
    keywords: ['relaxation', 'muscles', 'tension', 'calm', 'body'],
    steps: [
      'Find a quiet place',
      'Tense and release each muscle group',
      'Start with your feet',
      'Work your way up',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'nature-sound',
    title: 'Listen to nature sounds',
    emoji: '🌿',
    category: 'mindfulness',
    keywords: ['nature', 'sounds', 'relax', 'calm', 'peaceful'],
    steps: [
      'Find nature sounds online or app',
      'Put on headphones',
      'Listen for 5 minutes',
      'Focus on the sounds',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'affirmations',
    title: 'Say 3 positive affirmations',
    emoji: '💫',
    category: 'mindfulness',
    keywords: ['affirmations', 'positive', 'self-talk', 'encourage', 'mindset'],
    steps: [
      'Think of 3 things you want to affirm',
      'Say them out loud or in your head',
      'Repeat them 3 times each',
      'Feel the positivity',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },

  // ============================================================================
  // TRANSITION TASKS
  // ============================================================================
  {
    id: 'get-started',
    title: 'Get started on something',
    emoji: '🚀',
    category: 'self-care',
    keywords: ['start', 'begin', 'transition', 'getting started', 'first step'],
    steps: [
      'Pick one small thing to start',
      'Set a timer for 5 minutes',
      'Do just that one thing',
      'You can stop when the timer goes off',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'switch-tasks',
    title: 'Switch between tasks',
    emoji: '🔄',
    category: 'self-care',
    keywords: ['switch', 'transition', 'change', 'move on', 'next thing'],
    steps: [
      'Notice you\'re done with the current thing',
      'Take one deep breath',
      'Decide what to do next',
      'Start the new thing',
    ],
    difficulty: 'easy',
    estimatedTime: '1 min',
  },
  {
    id: 'finish-task',
    title: 'Finish what you\'re doing',
    emoji: '✅',
    category: 'self-care',
    keywords: ['finish', 'complete', 'done', 'ending', 'wrap up'],
    steps: [
      'Notice you\'re almost done',
      'Do one last small thing',
      'Put things away if needed',
      'Acknowledge you finished',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'leave-house',
    title: 'Get ready to leave the house',
    emoji: '🚪',
    category: 'self-care',
    keywords: ['leave', 'go out', 'transition', 'preparing', 'departure'],
    steps: [
      'Check you have keys and phone',
      'Put on shoes or jacket if needed',
      'Take one last look around',
      'You\'re ready to go',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'come-home',
    title: 'Transition back home',
    emoji: '🏠',
    category: 'self-care',
    keywords: ['home', 'arrive', 'transition', 'returning', 'settle'],
    steps: [
      'Put your things down',
      'Take off shoes or jacket',
      'Take 3 deep breaths',
      'Notice you\'re home now',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'wind-down',
    title: 'Wind down for the day',
    emoji: '🌙',
    category: 'self-care',
    keywords: ['wind down', 'evening', 'transition', 'relax', 'prepare for rest'],
    steps: [
      'Notice the day is ending',
      'Do one calming thing',
      'Put away what you can',
      'Give yourself permission to rest',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },

  // ============================================================================
  // RECOVERY & REPAIR TASKS
  // ============================================================================
  {
    id: 'restart-gently',
    title: 'Restart gently after a break',
    emoji: '🌱',
    category: 'self-care',
    keywords: ['restart', 'recovery', 'begin again', 'fresh start', 'reset'],
    steps: [
      'Acknowledge you\'re starting again',
      'Pick one tiny thing to do',
      'Do it without pressure',
      'That\'s enough for now',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'clean-up-yesterday',
    title: 'Clean up one thing from yesterday',
    emoji: '🧹',
    category: 'cleaning',
    keywords: ['clean up', 'yesterday', 'recovery', 'catch up', 'repair'],
    steps: [
      'Look for one small thing left undone',
      'It can be very small',
      'Do just that one thing',
      'You don\'t have to do everything',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'send-late-reply',
    title: 'Send a late reply',
    emoji: '📧',
    category: 'communication',
    keywords: ['reply', 'late', 'recovery', 'catch up', 'message'],
    steps: [
      'Open the message you missed',
      'Write a short, honest reply',
      'You don\'t need to apologize much',
      'Send it and move on',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'forgive-reset',
    title: 'Forgive yourself and reset',
    emoji: '💚',
    category: 'mindfulness',
    keywords: ['forgive', 'reset', 'recovery', 'self-compassion', 'fresh start'],
    steps: [
      'Notice any shame or guilt',
      'Remind yourself you\'re human',
      'Decide to start fresh',
      'Pick one small next step',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'recover-from-overwhelm',
    title: 'Recover from feeling overwhelmed',
    emoji: '🫂',
    category: 'self-care',
    keywords: ['overwhelm', 'recovery', 'calm', 'reset', 'regulate'],
    steps: [
      'Find a quiet spot',
      'Take 5 slow breaths',
      'Notice what you actually need right now',
      'Do just that one thing',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'restart-after-avoidance',
    title: 'Restart after avoiding something',
    emoji: '🔄',
    category: 'self-care',
    keywords: ['restart', 'avoidance', 'recovery', 'begin again', 'gentle'],
    steps: [
      'Acknowledge you avoided it',
      'That\'s okay, no judgment',
      'Pick the smallest possible step',
      'Do just that step',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },

  // ============================================================================
  // DECISION RELIEF TASKS
  // ============================================================================
  {
    id: 'pick-easiest',
    title: 'Pick the easiest option',
    emoji: '✨',
    category: 'planning',
    keywords: ['decide', 'easiest', 'choice', 'simple', 'decision relief'],
    steps: [
      'List 2-3 options',
      'Pick the one that feels easiest',
      'You don\'t need the perfect choice',
      'Go with that',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'decide-what-not-to-do',
    title: 'Decide what not to do',
    emoji: '✋',
    category: 'planning',
    keywords: ['decide', 'not to do', 'eliminate', 'simplify', 'choice'],
    steps: [
      'Look at your list or thoughts',
      'Pick one thing to skip today',
      'Give yourself permission',
      'Focus on what remains',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'choose-one-thing',
    title: 'Choose one thing and ignore the rest',
    emoji: '🎯',
    category: 'planning',
    keywords: ['choose', 'one thing', 'focus', 'simplify', 'decision'],
    steps: [
      'Look at everything you could do',
      'Pick just one thing',
      'Ignore everything else for now',
      'Do that one thing',
    ],
    difficulty: 'easy',
    estimatedTime: '1 min',
  },
  {
    id: 'minimum-viable',
    title: 'Do the minimum viable version',
    emoji: '📦',
    category: 'planning',
    keywords: ['minimum', 'viable', 'simplify', 'good enough', 'basic'],
    steps: [
      'Think of what you want to do',
      'Cut it in half',
      'Cut it in half again',
      'Do just that smaller version',
    ],
    difficulty: 'easy',
    estimatedTime: '3 min',
  },
  {
    id: 'flip-coin-decide',
    title: 'Flip a coin to decide',
    emoji: '🪙',
    category: 'planning',
    keywords: ['decide', 'coin', 'flip', 'choice', 'random'],
    steps: [
      'Name your two options',
      'Flip a coin or pick randomly',
      'Notice how you feel about the result',
      'Go with that feeling or the coin',
    ],
    difficulty: 'easy',
    estimatedTime: '1 min',
  },

  // ============================================================================
  // MENTAL OFFLOADING TASKS
  // ============================================================================
  {
    id: 'brain-dump',
    title: 'Do a brain dump',
    emoji: '🧠',
    category: 'mindfulness',
    keywords: ['brain dump', 'offload', 'thoughts', 'clear', 'write everything'],
    steps: [
      'Get paper or open notes',
      'Write everything on your mind',
      'Don\'t organize, just dump',
      'Stop when you feel lighter',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'note',
    linkedWidgetLabel: 'Notes',
  },
  {
    id: 'write-everything-down',
    title: 'Write everything down',
    emoji: '📝',
    category: 'mindfulness',
    keywords: ['write', 'everything', 'offload', 'thoughts', 'externalize'],
    steps: [
      'Open notes or get paper',
      'Write all your thoughts',
      'No structure needed',
      'Close it when done',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'note',
    linkedWidgetLabel: 'Notes',
  },
  {
    id: 'clear-headspace',
    title: 'Clear your headspace',
    emoji: '🧹',
    category: 'mindfulness',
    keywords: ['clear', 'headspace', 'mental', 'offload', 'reset'],
    steps: [
      'Get paper or voice notes',
      'Dump all swirling thoughts',
      'Don\'t judge or organize',
      'Notice the quiet after',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'note',
    linkedWidgetLabel: 'Notes',
  },
  {
    id: 'voice-dump',
    title: 'Record a voice note dump',
    emoji: '🎤',
    category: 'mindfulness',
    keywords: ['voice', 'record', 'dump', 'offload', 'speak'],
    steps: [
      'Open voice notes on your phone',
      'Press record',
      'Say everything on your mind',
      'Stop when you feel done',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'get-thoughts-out',
    title: 'Get thoughts out of your head',
    emoji: '💭',
    category: 'mindfulness',
    keywords: ['thoughts', 'externalize', 'offload', 'clear', 'mind'],
    steps: [
      'Choose paper, notes, or voice',
      'Start writing or speaking',
      'Keep going until you feel empty',
      'You can delete it later if you want',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
    linkedWidgetType: 'note',
    linkedWidgetLabel: 'Notes',
  },

  // ============================================================================
  // ENERGY-MATCHED TASKS
  // ============================================================================
  {
    id: 'low-energy-support',
    title: 'Do something for low energy',
    emoji: '🔋',
    category: 'self-care',
    keywords: ['low energy', 'tired', 'exhausted', 'gentle', 'rest'],
    steps: [
      'Acknowledge you have low energy',
      'Pick the gentlest option',
      'It can be very small',
      'Rest is also an option',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'high-energy-outlet',
    title: 'Channel high energy',
    emoji: '⚡',
    category: 'movement',
    keywords: ['high energy', 'restless', 'active', 'outlet', 'movement'],
    steps: [
      'Notice you have extra energy',
      'Pick something physical',
      'Dance, walk, or move',
      'Use the energy without judgment',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'calm-nervous-system',
    title: 'Calm your nervous system',
    emoji: '🫧',
    category: 'self-care',
    keywords: ['calm', 'nervous system', 'regulate', 'anxious', 'soothe'],
    steps: [
      'Find a quiet spot',
      'Take 5 slow, deep breaths',
      'Notice your body',
      'Stay here as long as needed',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'regulate-restless-body',
    title: 'Regulate a restless body',
    emoji: '🌊',
    category: 'movement',
    keywords: ['restless', 'regulate', 'body', 'movement', 'fidget'],
    steps: [
      'Notice the restlessness',
      'Do some gentle movement',
      'Stretch, shake, or walk',
      'Let the energy move through you',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'match-energy-to-task',
    title: 'Match your energy to a task',
    emoji: '⚖️',
    category: 'planning',
    keywords: ['energy', 'match', 'task', 'appropriate', 'realistic'],
    steps: [
      'Check in with your energy level',
      'Pick a task that matches it',
      'Low energy = gentle tasks',
      'High energy = active tasks',
    ],
    difficulty: 'easy',
    estimatedTime: '2 min',
  },
  {
    id: 'rest-when-needed',
    title: 'Rest when you need to',
    emoji: '😴',
    category: 'self-care',
    keywords: ['rest', 'tired', 'exhausted', 'permission', 'recovery'],
    steps: [
      'Notice you need rest',
      'Give yourself permission',
      'Find a comfortable spot',
      'Rest without guilt',
    ],
    difficulty: 'easy',
    estimatedTime: '10 min',
  },
  {
    id: 'gentle-movement',
    title: 'Do gentle movement',
    emoji: '🌿',
    category: 'movement',
    keywords: ['gentle', 'movement', 'low energy', 'soft', 'calm'],
    steps: [
      'Stand or sit comfortably',
      'Move your body slowly',
      'Stretch gently',
      'Stop when you feel done',
    ],
    difficulty: 'easy',
    estimatedTime: '5 min',
  },
  {
    id: 'active-movement',
    title: 'Do active movement',
    emoji: '🏃',
    category: 'movement',
    keywords: ['active', 'movement', 'high energy', 'exercise', 'cardio'],
    steps: [
      'Notice you have energy to move',
      'Pick something active',
      'Walk, dance, or exercise',
      'Use the energy',
    ],
    difficulty: 'easy',
    estimatedTime: '15 min',
  },
];

/**
 * Search tasks by keyword or category
 */
export function searchTasks(query: string, category?: TaskCategory): TaskTemplate[] {
  const lowerQuery = query.toLowerCase().trim();
  
  if (!lowerQuery && !category) {
    return TASK_LIBRARY;
  }

  return TASK_LIBRARY.filter(task => {
    // Category filter
    if (category && task.category !== category) {
      return false;
    }

    // Keyword search
    if (!lowerQuery) {
      return true;
    }

    // Search in title, keywords, and category
    const searchableText = [
      task.title.toLowerCase(),
      task.category.toLowerCase(),
      ...task.keywords.map(k => k.toLowerCase()),
    ].join(' ');

    return searchableText.includes(lowerQuery);
  });
}

/**
 * Get tasks by category
 */
export function getTasksByCategory(category: TaskCategory): TaskTemplate[] {
  return TASK_LIBRARY.filter(task => task.category === category);
}

/**
 * Get all categories
 */
export function getAllCategories(): TaskCategory[] {
  return Array.from(new Set(TASK_LIBRARY.map(task => task.category)));
}

/**
 * Get task by ID
 */
export function getTaskById(id: string): TaskTemplate | undefined {
  return TASK_LIBRARY.find(task => task.id === id);
}

/**
 * Get random suggested tasks (for initial display)
 */
export function getRandomSuggestions(count: number = 5): TaskTemplate[] {
  const shuffled = [...TASK_LIBRARY].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
