export interface TagData {
  name: string;
  title: string;
  description: string;
  longDescription: string;
  destination: string;
  destinationLabel: string;
  color: string;
  colorHex: string;
}

export const tagMapping: Record<string, TagData> = {
  Focus: {
    name: 'Focus',
    title: 'Protected Attention Without Pressure',
    description: 'Traditional tools demand endless focus. SharedMinds respects that attention is finite and valuable.',
    longDescription: 'Focus Mode creates short, intentional sessions designed around your actual energy levels—not arbitrary productivity standards. Focus Analytics reveal patterns in your attention over time, helping you understand what genuinely supports deep work without judgment or gamification.',
    destination: 'guardrails',
    destinationLabel: 'Explore Focus Features',
    color: 'from-blue-500 to-cyan-500',
    colorHex: '#3b82f6',
  },
  Capacity: {
    name: 'Capacity',
    title: 'Systems That Adapt to Your Energy',
    description: 'Capacity changes daily. SharedMinds helps you recognize and respect those fluctuations.',
    longDescription: 'Regulation tools help you notice when you\'re approaching overload before it becomes a crisis. Rather than pushing through or feeling guilty, SharedMinds provides awareness and gentle orientation—making it possible to adjust before burnout happens.',
    destination: 'regulation',
    destinationLabel: 'Learn About Regulation',
    color: 'from-blue-500 to-cyan-500',
    colorHex: '#3b82f6',
  },
  Rhythm: {
    name: 'Rhythm',
    title: 'Honoring Your Natural Patterns',
    description: 'Everyone has rhythms—times when they\'re sharp, times when they need rest. Most tools ignore this.',
    longDescription: 'SharedMinds helps you notice your patterns without forcing rigid schedules. Signals reveal when context-switching is happening too fast, when scope is expanding beyond capacity, or when you\'re fragmenting attention. This awareness lets you respond intentionally rather than reactively.',
    destination: 'regulation',
    destinationLabel: 'Explore Pattern Recognition',
    color: 'from-blue-500 to-cyan-500',
    colorHex: '#3b82f6',
  },
  Recovery: {
    name: 'Recovery',
    title: 'Rest as Part of the System',
    description: 'Productivity culture treats rest as weakness. SharedMinds treats it as necessary.',
    longDescription: 'Regulation isn\'t about maximizing output—it\'s about stabilizing the nervous system so that focus and clarity become possible. By recognizing stress, overload, and emotional friction early, SharedMinds supports recovery as a core function, not an afterthought.',
    destination: 'regulation',
    destinationLabel: 'Understand Regulation',
    color: 'from-blue-500 to-cyan-500',
    colorHex: '#3b82f6',
  },
  Tasks: {
    name: 'Tasks',
    title: 'From Intention to Action, Gently',
    description: 'Task lists are overwhelming when they don\'t match how your brain works. SharedMinds is different.',
    longDescription: 'Task Flow transforms ideas into manageable steps without rigid checklists or guilt-inducing backlogs. It supports non-linear thinking, letting you capture what needs to happen without forcing artificial hierarchies. Tasks stay connected to their broader context, making it easier to maintain momentum.',
    destination: 'guardrails',
    destinationLabel: 'Explore Task Flow',
    color: 'from-emerald-500 to-teal-500',
    colorHex: '#10b981',
  },
  Notes: {
    name: 'Notes',
    title: 'Capturing Thoughts Without Losing Them',
    description: 'Ideas appear when they want to—often at inconvenient times. SharedMinds makes it easy to capture them.',
    longDescription: 'Mind Mesh is a visual, node-based thinking space where ideas, goals, and tasks connect spatially. Instead of forcing everything into linear notes or lists, Mind Mesh supports the way your brain actually thinks—in connections, associations, and evolving relationships.',
    destination: 'guardrails',
    destinationLabel: 'See Mind Mesh',
    color: 'from-emerald-500 to-teal-500',
    colorHex: '#10b981',
  },
  Context: {
    name: 'Context',
    title: 'Making the Invisible Visible',
    description: 'Context is the invisible layer that makes everything make sense—or causes everything to fall apart.',
    longDescription: 'Spaces separate personal processing from shared responsibilities, making it possible to think privately while communicating intentionally. They honor that people organize information differently—linear lists, visual maps, narrative threads—without forcing one approach on everyone.',
    destination: 'spaces',
    destinationLabel: 'Explore Spaces',
    color: 'from-emerald-500 to-teal-500',
    colorHex: '#10b981',
  },
  Memory: {
    name: 'Memory',
    title: 'Externalizing What You Can\'t Hold',
    description: 'Working memory has limits. SharedMinds helps you stop trying to hold everything in your head.',
    longDescription: 'By externalizing tasks, context, decisions, and ideas into structured spaces, SharedMinds reduces cognitive load dramatically. Your mind becomes free for actual thinking rather than desperate storage. Context stays visible, accessible, and connected—reducing the mental effort of "where was I?"',
    destination: 'guardrails',
    destinationLabel: 'Learn About Mind Mesh',
    color: 'from-emerald-500 to-teal-500',
    colorHex: '#10b981',
  },
  Conversations: {
    name: 'Conversations',
    title: 'Shared Understanding, Not Just Shared Files',
    description: 'Teams fail when different people hold different pictures of the same reality.',
    longDescription: 'SharedMinds helps workplaces and teams create genuine shared context. When everyone can see how different minds are processing the same project, misalignment becomes visible before it causes conflict. Conversations become clearer because expectations, needs, and boundaries are explicit.',
    destination: 'use-cases#workplaces-teams',
    destinationLabel: 'See Team Use Cases',
    color: 'from-amber-500 to-orange-500',
    colorHex: '#f59e0b',
  },
  Clarity: {
    name: 'Clarity',
    title: 'Structure That Supports Understanding',
    description: 'Clarity isn\'t about simplicity—it\'s about making complexity workable.',
    longDescription: 'GuardRails provide structure without rigidity, helping ideas move forward without forcing them into workflows that don\'t fit your brain. Spaces make different perspectives visible, reducing misunderstandings and conflict. Together, they create clarity across minds, roles, and responsibilities.',
    destination: 'spaces',
    destinationLabel: 'Discover Clarity Tools',
    color: 'from-amber-500 to-orange-500',
    colorHex: '#f59e0b',
  },
  Coordination: {
    name: 'Coordination',
    title: 'Alignment Without Micromanagement',
    description: 'Coordination is cognitive labor—and most tools don\'t treat it that way.',
    longDescription: 'SharedMinds helps project managers and coordinators keep everything aligned without controlling how people work. It makes different perspectives visible, clarifies expectations, and helps you notice where communication is breaking down before it becomes a crisis. Coordination becomes sustainable rather than exhausting.',
    destination: 'use-cases#project-managers',
    destinationLabel: 'See Coordination Use Cases',
    color: 'from-amber-500 to-orange-500',
    colorHex: '#f59e0b',
  },
  Visibility: {
    name: 'Visibility',
    title: 'Making Perspectives Explicit',
    description: 'What\'s obvious to you is often invisible to others. SharedMinds makes this visible.',
    longDescription: 'Spaces help individuals, households, and teams understand how different minds experience the same world. By making perspectives explicit, SharedMinds reduces the constant low-level friction of "I thought you knew" or "I didn\'t realize that mattered to you." Visibility creates shared understanding.',
    destination: 'spaces',
    destinationLabel: 'Learn About Spaces',
    color: 'from-amber-500 to-orange-500',
    colorHex: '#f59e0b',
  },
};
