/**
 * Node Hover Preview
 *
 * Shows basic relationship information on hover over a node.
 * Appears near the cursor without blocking interaction.
 */

interface NodeHoverPreviewProps {
  relationshipLabel: string;
  directionLabel: string;
  isAutoGenerated: boolean;
  position: { x: number; y: number };
}

export function NodeHoverPreview({
  relationshipLabel,
  directionLabel,
  isAutoGenerated,
  position,
}: NodeHoverPreviewProps) {
  return (
    <div
      className="fixed z-[1000] pointer-events-none"
      style={{
        left: position.x + 20,
        top: position.y - 10,
      }}
    >
      <div className="bg-white border border-gray-300 rounded-lg shadow-lg p-3 max-w-xs">
        <div className="flex items-center gap-2 mb-1.5">
          <span className="text-xs font-medium text-gray-600">{relationshipLabel}</span>
          <div
            className={`ml-auto px-2 py-0.5 rounded text-xs font-medium ${
              isAutoGenerated
                ? 'bg-gray-100 text-gray-600'
                : 'bg-green-100 text-green-700'
            }`}
          >
            {isAutoGenerated ? 'Auto' : 'Manual'}
          </div>
        </div>

        <div className="text-sm text-gray-900 mb-2">
          {directionLabel}
        </div>

        <div className="text-xs text-gray-500 border-t border-gray-200 pt-2">
          {isAutoGenerated
            ? 'Derived from Guardrails structure'
            : 'Created manually in Mind Mesh'}
        </div>
      </div>
    </div>
  );
}
