/**
 * Node Inspector
 *
 * Side panel showing detailed read-only information about a node (relationship).
 * Opens on click, closes on explicit close or deselect.
 */

import { useState } from 'react';
import { X, ArrowRight, Trash2 } from 'lucide-react';
import type { NodeMetadata } from '../../../lib/mindmesh-v2/nodeMetadata';
import { ConfirmDialog } from '../../ConfirmDialog';

interface NodeInspectorProps {
  metadata: NodeMetadata;
  createdAt: string;
  nodeId: string;
  canEdit: boolean;
  onClose: () => void;
  onDelete?: (nodeId: string) => void;
}

export function NodeInspector({
  metadata,
  createdAt,
  nodeId,
  canEdit,
  onClose,
  onDelete,
}: NodeInspectorProps) {
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  return (
    <>
      <ConfirmDialog
        isOpen={showDeleteConfirm}
        onClose={() => setShowDeleteConfirm(false)}
        onConfirm={() => {
          setShowDeleteConfirm(false);
          if (onDelete) {
            onDelete(nodeId);
          }
        }}
        title="Delete Connection"
        message="Are you sure you want to delete this connection? This action cannot be undone."
        confirmText="Delete"
        cancelText="Cancel"
        variant="danger"
      />
    <div className="absolute top-0 right-0 h-full w-80 bg-white border-l border-gray-200 shadow-lg z-40 overflow-y-auto">
      {/* Header */}
      <div className="p-4 border-b border-gray-200 flex items-center justify-between">
        <h3 className="text-lg font-semibold text-gray-900">Relationship Inspector</h3>
        <button
          onClick={onClose}
          className="p-1 hover:bg-gray-100 rounded transition-colors"
          aria-label="Close inspector"
        >
          <X className="h-5 w-5 text-gray-500" />
        </button>
      </div>

      {/* Content */}
      <div className="p-4 space-y-4">
        {/* Status Badge */}
        <div>
          <div
            className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium ${
              metadata.isAutoGenerated
                ? 'bg-gray-100 text-gray-700 border border-gray-300'
                : 'bg-green-100 text-green-700 border border-green-300'
            }`}
          >
            <div className={`w-2 h-2 rounded-full ${metadata.isAutoGenerated ? 'bg-gray-500' : 'bg-green-500'}`} />
            {metadata.isAutoGenerated ? 'Auto-Generated' : 'Manual'}
          </div>
        </div>

        {/* Relationship Type */}
        <div>
          <label className="block text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">
            Relationship Type
          </label>
          <div className="text-sm text-gray-900 font-medium">{metadata.relationshipLabel}</div>
        </div>

        {/* Direction */}
        <div>
          <label className="block text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">
            Direction
          </label>
          <div className="text-sm text-gray-900">{metadata.directionLabel}</div>
        </div>

        {/* Connected Containers */}
        <div>
          <label className="block text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">
            Connected Containers
          </label>
          <div className="space-y-3">
            {/* Source Container */}
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-3">
              <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">
                Source
              </div>
              <div className="text-sm font-medium text-gray-900">{metadata.sourceContainer.title}</div>
              <div className="text-xs text-gray-500 mt-1 font-mono">
                {metadata.sourceContainer.entityType}
              </div>
            </div>

            {/* Arrow */}
            <div className="flex justify-center">
              <ArrowRight className="h-5 w-5 text-gray-400" />
            </div>

            {/* Target Container */}
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-3">
              <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">
                Target
              </div>
              <div className="text-sm font-medium text-gray-900">{metadata.targetContainer.title}</div>
              <div className="text-xs text-gray-500 mt-1 font-mono">
                {metadata.targetContainer.entityType}
              </div>
            </div>
          </div>
        </div>

        {/* Description */}
        <div>
          <label className="block text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">
            Description
          </label>
          <div className="text-sm text-gray-700 leading-relaxed">
            {metadata.description}
          </div>
        </div>

        {/* Technical Details */}
        <div className="border-t border-gray-200 pt-4">
          <label className="block text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">
            Technical
          </label>
          <div className="space-y-1.5 text-xs text-gray-500">
            <div className="flex justify-between">
              <span>Created:</span>
              <span>{new Date(createdAt).toLocaleString()}</span>
            </div>
            <div className="flex justify-between">
              <span>Type:</span>
              <span className="font-mono">{metadata.relationshipType}</span>
            </div>
            <div className="flex justify-between">
              <span>Source:</span>
              <span className="font-mono">
                {metadata.isAutoGenerated ? 'guardrails' : 'manual'}
              </span>
            </div>
          </div>
        </div>

        {/* Delete Connection Button (Manual nodes only) */}
        {!metadata.isAutoGenerated && onDelete && (
          <div className="border-t border-gray-200 pt-4">
            <button
              onClick={() => setShowDeleteConfirm(true)}
              disabled={!canEdit}
              className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-red-50 text-red-700 border border-red-300 rounded-lg hover:bg-red-100 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              title={canEdit ? 'Delete this connection' : 'Acquire canvas lock to delete'}
            >
              <Trash2 className="h-4 w-4" />
              <span className="font-medium">Delete Connection</span>
            </button>
            {!canEdit && (
              <p className="text-xs text-amber-600 mt-2 text-center">
                Acquire canvas lock to delete
              </p>
            )}
          </div>
        )}
      </div>
    </div>
    </>
  );
}
