// ProjectShareService — external accountability shares for a single
// project. Generates url-safe tokens, lists / revokes existing tokens,
// and reads the public shared view (used by the unauth /shared/:token
// route).
//
// All owner operations are RLS-gated to the project's created_by. The
// public read goes through the get_shared_project_view RPC which is
// SECURITY DEFINER and validates the token server-side.

import { supabase } from '../../lib/supabase';

export interface ProjectShareToken {
  id: string;
  project_id: string;
  token: string;
  invited_label: string | null;
  invited_email: string | null;
  created_by: string;
  expires_at: string | null;
  revoked_at: string | null;
  weekly_summary_email: boolean;
  last_viewed_at: string | null;
  created_at: string;
}

/** Shape returned by the public RPC. Errors come back as {error:string}. */
export interface SharedProjectView {
  project: {
    id: string;
    title: string;
    description: string | null;
    color: string | null;
    cover_image_url: string | null;
    cover_x: number;
    cover_y: number;
    cover_zoom: number;
    cover_fit: 'cover' | 'contain';
    cover_bg_color: string | null;
    cover_text_color: 'light' | 'dark';
    created_at: string;
    target_date: string | null;
    status: string;
  };
  ownerFirstName: string;
  sessions: SharedSession[];
}

export interface SharedSession {
  id: string;
  session_goal: string | null;
  session_title: string | null;
  session_outcome: 'finished' | 'partially' | 'something_came_up' | 'no_answer';
  session_mode: string | null;
  is_offline: boolean;
  intended_duration_minutes: number | null;
  ended_at: string | null;
  start_time: string;
}

export const ProjectShareService = {
  /** Create a new share token for a project. The token field is
   *  generated by the DB default; we never set it from the client. */
  async createToken(input: {
    projectId: string;
    invitedLabel?: string | null;
    invitedEmail?: string | null;
    weeklySummaryEmail?: boolean;
  }): Promise<ProjectShareToken> {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) throw new Error('Not authenticated');
    const { data, error } = await supabase
      .from('project_share_tokens')
      .insert({
        project_id: input.projectId,
        invited_label: input.invitedLabel?.trim() || null,
        invited_email: input.invitedEmail?.trim() || null,
        weekly_summary_email: !!input.weeklySummaryEmail,
        created_by: user.id,
      })
      .select()
      .single();
    if (error) throw error;
    return data as ProjectShareToken;
  },

  /** List active + revoked tokens for a project. Owner only via RLS. */
  async listTokens(projectId: string): Promise<ProjectShareToken[]> {
    const { data, error } = await supabase
      .from('project_share_tokens')
      .select('*')
      .eq('project_id', projectId)
      .order('created_at', { ascending: false });
    if (error) {
      console.error('[ProjectShareService] listTokens', error);
      return [];
    }
    return (data ?? []) as ProjectShareToken[];
  },

  /** Mark a token revoked. Use this rather than DELETE so the row
   *  survives for audit / "Mum had access for X days" context. */
  async revokeToken(tokenId: string): Promise<void> {
    const { error } = await supabase
      .from('project_share_tokens')
      .update({ revoked_at: new Date().toISOString() })
      .eq('id', tokenId);
    if (error) throw error;
  },

  /** Permanently delete a token row. RLS gates to owner. */
  async deleteToken(tokenId: string): Promise<void> {
    const { error } = await supabase
      .from('project_share_tokens')
      .delete()
      .eq('id', tokenId);
    if (error) throw error;
  },

  /** Public read — fetch the share view for a token. Returns null if
   *  the token is invalid / expired / revoked / project gone. */
  async fetchSharedView(token: string): Promise<SharedProjectView | null> {
    const { data, error } = await supabase.rpc('get_shared_project_view', { p_token: token });
    if (error) {
      console.error('[ProjectShareService] fetchSharedView', error);
      return null;
    }
    const blob = data as any;
    if (!blob || blob.error) return null;
    return blob as SharedProjectView;
  },

  /** Build the absolute URL for a given token — copyable for the user. */
  buildShareUrl(token: string): string {
    const origin = typeof window !== 'undefined' ? window.location.origin : '';
    return `${origin}/shared/${token}`;
  },
};
