import { supabase } from '../supabase';
import type {
  MindMeshWidget,
  MindMeshConnection,
  CreateMindMeshWidgetInput,
  UpdateMindMeshWidgetInput,
  CreateMindMeshConnectionInput,
  ConnectionSourceType,
  ConnectionTargetType,
} from './coreTypes';

const WIDGETS_TABLE = 'mindmesh_widgets';
const CONNECTIONS_TABLE = 'mindmesh_connections';

function camelToSnake(str: string): string {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

function transformKeysToSnake(obj: Record<string, any>): Record<string, any> {
  const result: Record<string, any> = {};
  for (const [key, value] of Object.entries(obj)) {
    result[camelToSnake(key)] = value;
  }
  return result;
}

function transformWidgetFromDb(row: any): MindMeshWidget {
  return {
    id: row.id,
    masterProjectId: row.master_project_id,
    type: row.type,
    title: row.title,
    content: row.content,
    xPosition: row.x_position,
    yPosition: row.y_position,
    width: row.width,
    height: row.height,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function transformConnectionFromDb(row: any): MindMeshConnection {
  return {
    id: row.id,
    masterProjectId: row.master_project_id,
    sourceType: row.source_type,
    sourceId: row.source_id,
    targetType: row.target_type,
    targetId: row.target_id,
    relationship: row.relationship,
    autoGenerated: row.auto_generated,
    createdAt: row.created_at,
  };
}

export async function createWidget(input: CreateMindMeshWidgetInput): Promise<MindMeshWidget> {
  const dbInput = transformKeysToSnake(input);

  const { data, error } = await supabase
    .from(WIDGETS_TABLE)
    .insert(dbInput)
    .select()
    .single();

  if (error) throw error;
  return transformWidgetFromDb(data);
}

export async function updateWidget(
  id: string,
  input: UpdateMindMeshWidgetInput
): Promise<MindMeshWidget> {
  const dbInput = transformKeysToSnake(input);

  const { data, error } = await supabase
    .from(WIDGETS_TABLE)
    .update(dbInput)
    .eq('id', id)
    .select()
    .single();

  if (error) throw error;
  return transformWidgetFromDb(data);
}

export async function deleteWidget(id: string): Promise<void> {
  const { error } = await supabase
    .from(WIDGETS_TABLE)
    .delete()
    .eq('id', id);

  if (error) throw error;
}

export async function getWidget(id: string): Promise<MindMeshWidget | null> {
  const { data, error } = await supabase
    .from(WIDGETS_TABLE)
    .select('*')
    .eq('id', id)
    .maybeSingle();

  if (error) throw error;
  if (!data) return null;

  return transformWidgetFromDb(data);
}

export async function getWidgetsByProject(masterProjectId: string): Promise<MindMeshWidget[]> {
  const { data, error } = await supabase
    .from(WIDGETS_TABLE)
    .select('*')
    .eq('master_project_id', masterProjectId)
    .order('created_at', { ascending: true });

  if (error) throw error;
  return (data || []).map(transformWidgetFromDb);
}

export async function createConnection(
  input: CreateMindMeshConnectionInput
): Promise<MindMeshConnection> {
  const dbInput = transformKeysToSnake(input);

  const { data, error } = await supabase
    .from(CONNECTIONS_TABLE)
    .insert(dbInput)
    .select()
    .single();

  if (error) throw error;
  return transformConnectionFromDb(data);
}

export async function deleteConnection(id: string): Promise<void> {
  const { error } = await supabase
    .from(CONNECTIONS_TABLE)
    .delete()
    .eq('id', id);

  if (error) throw error;
}

export async function getConnection(id: string): Promise<MindMeshConnection | null> {
  const { data, error } = await supabase
    .from(CONNECTIONS_TABLE)
    .select('*')
    .eq('id', id)
    .maybeSingle();

  if (error) throw error;
  if (!data) return null;

  return transformConnectionFromDb(data);
}

export async function getConnectionsByProject(
  masterProjectId: string
): Promise<MindMeshConnection[]> {
  const { data, error } = await supabase
    .from(CONNECTIONS_TABLE)
    .select('*')
    .eq('master_project_id', masterProjectId)
    .order('created_at', { ascending: true});

  if (error) throw error;
  return (data || []).map(transformConnectionFromDb);
}

export async function getConnectionsForNode(
  nodeType: ConnectionSourceType | ConnectionTargetType,
  nodeId: string
): Promise<MindMeshConnection[]> {
  const { data: sourceConnections, error: sourceError } = await supabase
    .from(CONNECTIONS_TABLE)
    .select('*')
    .eq('source_type', nodeType)
    .eq('source_id', nodeId);

  if (sourceError) throw sourceError;

  const { data: targetConnections, error: targetError } = await supabase
    .from(CONNECTIONS_TABLE)
    .select('*')
    .eq('target_type', nodeType)
    .eq('target_id', nodeId);

  if (targetError) throw targetError;

  const allConnections = [
    ...(sourceConnections || []),
    ...(targetConnections || []),
  ];

  const uniqueConnections = Array.from(
    new Map(allConnections.map(conn => [conn.id, conn])).values()
  );

  return uniqueConnections.map(transformConnectionFromDb);
}

export async function getAutoGeneratedConnections(
  masterProjectId: string
): Promise<MindMeshConnection[]> {
  const { data, error } = await supabase
    .from(CONNECTIONS_TABLE)
    .select('*')
    .eq('master_project_id', masterProjectId)
    .eq('auto_generated', true);

  if (error) throw error;
  return (data || []).map(transformConnectionFromDb);
}

export async function getManualConnections(
  masterProjectId: string
): Promise<MindMeshConnection[]> {
  const { data, error } = await supabase
    .from(CONNECTIONS_TABLE)
    .select('*')
    .eq('master_project_id', masterProjectId)
    .eq('auto_generated', false);

  if (error) throw error;
  return (data || []).map(transformConnectionFromDb);
}

export async function deleteAutoGeneratedConnectionsForNode(
  nodeType: ConnectionSourceType | ConnectionTargetType,
  nodeId: string
): Promise<void> {
  await supabase
    .from(CONNECTIONS_TABLE)
    .delete()
    .eq('source_type', nodeType)
    .eq('source_id', nodeId)
    .eq('auto_generated', true);

  await supabase
    .from(CONNECTIONS_TABLE)
    .delete()
    .eq('target_type', nodeType)
    .eq('target_id', nodeId)
    .eq('auto_generated', true);
}

export interface MindMeshGraph {
  widgets: MindMeshWidget[];
  connections: MindMeshConnection[];
}

export async function getMindMeshGraph(masterProjectId: string): Promise<MindMeshGraph> {
  const [widgets, connections] = await Promise.all([
    getWidgetsByProject(masterProjectId),
    getConnectionsByProject(masterProjectId),
  ]);

  return { widgets, connections };
}
