export type MindMeshSourceType =
  | 'track'
  | 'roadmap_item'
  | 'person'
  | 'document'
  | 'idea';

export type MindMeshEdgeType =
  | 'hierarchy'
  | 'reference'
  | 'composition'
  | 'ideation'
  | 'influence'
  | 'derivation'
  | 'dependency'
  | 'supporting'
  | 'offshoot';

export type MindMeshEdgeDirection = 'directed' | 'undirected';

export type MindMeshVisibilityState = 'visible' | 'hidden' | 'collapsed';

export interface MindMeshNodeExtended {
  id: string;
  masterProjectId: string;
  trackId: string | null;
  subtrackId: string | null;
  title: string;
  content: string;
  nodeType: string;
  label: string | null;
  sourceType: MindMeshSourceType | null;
  sourceId: string | null;
  autoGenerated: boolean;
  metadata: Record<string, any>;
  xPosition: number;
  yPosition: number;
  width: number;
  height: number;
  color: string;
  isOffshoot: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface MindMeshEdge {
  id: string;
  fromNodeId: string;
  toNodeId: string;
  linkType: string;
  edgeType: MindMeshEdgeType | null;
  direction: MindMeshEdgeDirection;
  autoGenerated: boolean;
  label: string | null;
  weight: number;
  createdAt: string;
}

export interface MindMeshVisibilityPreference {
  id: string;
  userId: string;
  masterProjectId: string;
  nodeId: string | null;
  edgeId: string | null;
  visibilityState: MindMeshVisibilityState;
  createdAt: string;
  updatedAt: string;
}

export interface CreateAutoNodeInput {
  masterProjectId: string;
  sourceType: MindMeshSourceType;
  sourceId: string;
  label: string;
  metadata?: Record<string, any>;
  xPosition?: number;
  yPosition?: number;
  color?: string;
}

export interface CreateManualNodeInput {
  masterProjectId: string;
  label: string;
  content?: string;
  xPosition?: number;
  yPosition?: number;
  width?: number;
  height?: number;
  color?: string;
  metadata?: Record<string, any>;
}

export interface CreateAutoEdgeInput {
  fromNodeId: string;
  toNodeId: string;
  edgeType: MindMeshEdgeType;
  direction?: MindMeshEdgeDirection;
  label?: string;
}

export interface CreateManualEdgeInput {
  fromNodeId: string;
  toNodeId: string;
  edgeType: MindMeshEdgeType;
  direction?: MindMeshEdgeDirection;
  label?: string;
  weight?: number;
}

export interface UpdateNodePositionInput {
  nodeId: string;
  xPosition: number;
  yPosition: number;
}

export interface UpdateNodeInput {
  label?: string;
  content?: string;
  xPosition?: number;
  yPosition?: number;
  width?: number;
  height?: number;
  color?: string;
  metadata?: Record<string, any>;
}

export interface MindMeshGraphData {
  nodes: MindMeshNodeExtended[];
  edges: MindMeshEdge[];
  visibilityPreferences: MindMeshVisibilityPreference[];
}

export interface NodeNeighbors {
  node: MindMeshNodeExtended;
  incomingEdges: MindMeshEdge[];
  outgoingEdges: MindMeshEdge[];
  incomingNodes: MindMeshNodeExtended[];
  outgoingNodes: MindMeshNodeExtended[];
}

export interface GraphStatistics {
  totalNodes: number;
  autoGeneratedNodes: number;
  manualNodes: number;
  nodesBySourceType: Record<MindMeshSourceType, number>;
  totalEdges: number;
  autoGeneratedEdges: number;
  manualEdges: number;
  edgesByType: Record<MindMeshEdgeType, number>;
  hiddenNodesCount: number;
  hiddenEdgesCount: number;
}

export interface AutoGenerationRules {
  generateTrackHierarchy: boolean;
  generateRoadmapItemNodes: boolean;
  generatePeopleNodes: boolean;
  generateTrackToItemEdges: boolean;
  generateItemToPeopleEdges: boolean;
}

export interface GraphLayer {
  id: string;
  name: string;
  nodeTypes: MindMeshSourceType[];
  edgeTypes: MindMeshEdgeType[];
  visible: boolean;
}

export interface FocusContext {
  centerNodeId: string;
  depth: number;
  includeAutoGenerated: boolean;
  includeManual: boolean;
}

export interface GraphQuery {
  masterProjectId: string;
  includeAutoGenerated?: boolean;
  includeManual?: boolean;
  sourceTypes?: MindMeshSourceType[];
  edgeTypes?: MindMeshEdgeType[];
  respectVisibility?: boolean;
  userId?: string;
}

export interface NodeSearchResult {
  node: MindMeshNodeExtended;
  score: number;
  matchType: 'label' | 'content' | 'metadata';
}

export interface GraphValidationResult {
  isValid: boolean;
  orphanedNodes: MindMeshNodeExtended[];
  invalidEdges: MindMeshEdge[];
  missingSourceReferences: MindMeshNodeExtended[];
}

export interface AutoGenerationResult {
  nodesCreated: number;
  edgesCreated: number;
  nodesUpdated: number;
  errors: string[];
}

export interface GraphDiff {
  nodesAdded: MindMeshNodeExtended[];
  nodesRemoved: MindMeshNodeExtended[];
  nodesUpdated: MindMeshNodeExtended[];
  edgesAdded: MindMeshEdge[];
  edgesRemoved: MindMeshEdge[];
}
