-- Dusk album — seed the 31 real tracks.
--
-- v8 of the music guide added `dusk` as the 9th category — Middle
-- Eastern modal scales (oud, ney, maqam-based melodies) targeting
-- theta-alpha 8 Hz for the "creative / contemplative" mental state.
--
-- 15 prompts × 2 Suno variants + a single "Ledger of Stone" track
-- whose duplicate Suno didn't generate = 31 files. The "(1)" sibling
-- of each prompt has been renamed to its own poetic title rather
-- than carrying a numeric suffix, so each pair reads as two distinct
-- tracks (e.g. Caravanserai + Silk Road, Hammam + Marble Hammam).
--
-- Storage prefix: session-music/dusk/. Filenames are slugified
-- lowercase + hyphenated (so "Court of Lions" → court-of-lions.mp3).
-- Upload MP3s with the matching names before users play.

INSERT INTO public.session_tracks (title, artist, category, file_path, attribution) VALUES
  -- Caravan pair
  ('Caravanserai',          'Generated by Suno', 'dusk', 'dusk/caravanserai.mp3',          'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Silk Road',             'Generated by Suno', 'dusk', 'dusk/silk-road.mp3',             'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Desert stillness pair
  ('Desert Stillness',      'Generated by Suno', 'dusk', 'dusk/desert-stillness.mp3',      'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Dune Hush',             'Generated by Suno', 'dusk', 'dusk/dune-hush.mp3',             'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Desert trance pair
  ('Desert Trance',         'Generated by Suno', 'dusk', 'dusk/desert-trance.mp3',         'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Sand Mirage',           'Generated by Suno', 'dusk', 'dusk/sand-mirage.mp3',           'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Pastures pair
  ('Forgotten Pastures',    'Generated by Suno', 'dusk', 'dusk/forgotten-pastures.mp3',    'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Wandering Pastures',    'Generated by Suno', 'dusk', 'dusk/wandering-pastures.mp3',    'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Hammam pair
  ('Hammam',                'Generated by Suno', 'dusk', 'dusk/hammam.mp3',                'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Marble Hammam',         'Generated by Suno', 'dusk', 'dusk/marble-hammam.mp3',         'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Harbor lullaby pair
  ('Harbor Lullaby',        'Generated by Suno', 'dusk', 'dusk/harbor-lullaby.mp3',        'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Quay Lullaby',          'Generated by Suno', 'dusk', 'dusk/quay-lullaby.mp3',          'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Harbor nights pair
  ('Harbor Nights',         'Generated by Suno', 'dusk', 'dusk/harbor-nights.mp3',         'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Harbor Stars',          'Generated by Suno', 'dusk', 'dusk/harbor-stars.mp3',          'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Pattern pair
  ('Infinite Pattern',      'Generated by Suno', 'dusk', 'dusk/infinite-pattern.mp3',      'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Endless Tile',          'Generated by Suno', 'dusk', 'dusk/endless-tile.mp3',          'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Alhambra pair
  ('La Alhambra',           'Generated by Suno', 'dusk', 'dusk/la-alhambra.mp3',           'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Court of Lions',        'Generated by Suno', 'dusk', 'dusk/court-of-lions.mp3',        'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Ledger (solo — no Suno sibling generated)
  ('Ledger of Stone',       'Generated by Suno', 'dusk', 'dusk/ledger-of-stone.mp3',       'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Maqam pair
  ('Maqam Study',           'Generated by Suno', 'dusk', 'dusk/maqam-study.mp3',           'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Hijaz Study',           'Generated by Suno', 'dusk', 'dusk/hijaz-study.mp3',           'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Midnight pair
  ('Midnight Oil',          'Generated by Suno', 'dusk', 'dusk/midnight-oil.mp3',          'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Late Lamp',             'Generated by Suno', 'dusk', 'dusk/late-lamp.mp3',             'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Mirage pair
  ('Mirage',                'Generated by Suno', 'dusk', 'dusk/mirage.mp3',                'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Heat Shimmer',          'Generated by Suno', 'dusk', 'dusk/heat-shimmer.mp3',          'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Saudade pair
  ('Saudade Sem Fim',       'Generated by Suno', 'dusk', 'dusk/saudade-sem-fim.mp3',       'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Saudade do Mar',        'Generated by Suno', 'dusk', 'dusk/saudade-do-mar.mp3',        'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Well of stars pair
  ('The Well of Stars',     'Generated by Suno', 'dusk', 'dusk/the-well-of-stars.mp3',     'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Star Cistern',          'Generated by Suno', 'dusk', 'dusk/star-cistern.mp3',          'Suno v2 — Dusk (theta–alpha 8 Hz)'),
  -- Whispers pair
  ('Whispers of the Desert','Generated by Suno', 'dusk', 'dusk/whispers-of-the-desert.mp3','Suno v2 — Dusk (theta–alpha 8 Hz)'),
  ('Whispering Dunes',      'Generated by Suno', 'dusk', 'dusk/whispering-dunes.mp3',      'Suno v2 — Dusk (theta–alpha 8 Hz)')
ON CONFLICT (file_path) DO NOTHING;
