-- Score album — replace the placeholder seed with the actual 29 tracks.
--
-- Migration 20260527000007 seeded 10 Score rows using the track names
-- from the music-guide v6 spec, but Suno's actual outputs landed with
-- different titles. There are 29 real files — 14 base prompts each
-- generated a primary + sibling variant, plus "Upward Offering" got
-- three variants. Rather than calling siblings "II" we gave each one
-- its own thematic name so they read as proper distinct tracks (e.g.
-- "Canopy of Ancients" + "Elder Canopy", "Cathedral Vastness" + "Vast
-- Stone"). This migration:
--
--   1. Removes the old placeholder Score rows so they can't drift into
--      404-on-play if a client tries to fetch one of the dud paths.
--   2. Inserts the 29 real tracks with file_paths matching the
--      slugified filenames uploaded to the session-music bucket under
--      `score/`.
--
-- Drive album is untouched — those rows still match real uploads.

-- ── 1. Drop the placeholder rows ──────────────────────────────────────
--
-- Match by file_path to be surgical — the placeholder set used
-- "01-opening-frame.mp3"-style paths that don't collide with anything
-- in the real set below.

DELETE FROM public.session_tracks
WHERE category = 'score'
  AND file_path IN (
    'score/01-opening-frame.mp3',
    'score/02-vast-interior.mp3',
    'score/03-the-atlas.mp3',
    'score/04-slow-magnitude.mp3',
    'score/05-meridian.mp3',
    'score/06-pale-distance.mp3',
    'score/07-the-quiet-work.mp3',
    'score/08-unseen-hours.mp3',
    'score/09-continental.mp3',
    'score/10-the-weight.mp3'
  );

-- ── 2. Seed the real Score tracks ─────────────────────────────────────
--
-- file_path uses lowercased, hyphenated title under the score/ prefix.
-- Each base prompt has a thematic sibling (the "(1)" Suno duplicate
-- renamed to its own poetic title) so the album feels curated rather
-- than auto-numbered. Upload MP3s to session-music/score/ with these
-- exact filenames before users play.

INSERT INTO public.session_tracks (title, artist, category, file_path, attribution) VALUES
  -- Canopy pair
  ('Canopy of Ancients',     'Generated by Suno', 'score', 'score/canopy-of-ancients.mp3',     'Suno v2 — Score (alpha 12 Hz)'),
  ('Elder Canopy',           'Generated by Suno', 'score', 'score/elder-canopy.mp3',           'Suno v2 — Score (alpha 12 Hz)'),
  -- Cathedral pair
  ('Cathedral Vastness',     'Generated by Suno', 'score', 'score/cathedral-vastness.mp3',     'Suno v2 — Score (alpha 12 Hz)'),
  ('Vast Stone',             'Generated by Suno', 'score', 'score/vast-stone.mp3',             'Suno v2 — Score (alpha 12 Hz)'),
  -- Silence pair
  ('Chosen Silence',         'Generated by Suno', 'score', 'score/chosen-silence.mp3',         'Suno v2 — Score (alpha 12 Hz)'),
  ('Silence Held',           'Generated by Suno', 'score', 'score/silence-held.mp3',           'Suno v2 — Score (alpha 12 Hz)'),
  -- Dorian pair
  ('Cold Stone Dorian',      'Generated by Suno', 'score', 'score/cold-stone-dorian.mp3',      'Suno v2 — Score (alpha 12 Hz)'),
  ('Dorian in Cold Stone',   'Generated by Suno', 'score', 'score/dorian-in-cold-stone.mp3',   'Suno v2 — Score (alpha 12 Hz)'),
  -- Morning pair
  ('First Draft of Morning', 'Generated by Suno', 'score', 'score/first-draft-of-morning.mp3', 'Suno v2 — Score (alpha 12 Hz)'),
  ('Morning Drafted',        'Generated by Suno', 'score', 'score/morning-drafted.mp3',        'Suno v2 — Score (alpha 12 Hz)'),
  -- Hall-of-light pair
  ('First Light Hall',       'Generated by Suno', 'score', 'score/first-light-hall.mp3',       'Suno v2 — Score (alpha 12 Hz)'),
  ('Lantern Hall',           'Generated by Suno', 'score', 'score/lantern-hall.mp3',           'Suno v2 — Score (alpha 12 Hz)'),
  -- Gravity / weighty hall pair
  ('Low Hall Gravity',       'Generated by Suno', 'score', 'score/low-hall-gravity.mp3',       'Suno v2 — Score (alpha 12 Hz)'),
  ('Heavy Hall',             'Generated by Suno', 'score', 'score/heavy-hall.mp3',             'Suno v2 — Score (alpha 12 Hz)'),
  -- Lament pair
  ('Open Water Lament',      'Generated by Suno', 'score', 'score/open-water-lament.mp3',      'Suno v2 — Score (alpha 12 Hz)'),
  ('Sea Lament',             'Generated by Suno', 'score', 'score/sea-lament.mp3',             'Suno v2 — Score (alpha 12 Hz)'),
  -- Sevenths pair
  ('Room of Sevenths',       'Generated by Suno', 'score', 'score/room-of-sevenths.mp3',       'Suno v2 — Score (alpha 12 Hz)'),
  ('The Seventh Room',       'Generated by Suno', 'score', 'score/the-seventh-room.mp3',       'Suno v2 — Score (alpha 12 Hz)'),
  -- Salon pair
  ('Salon Gears',            'Generated by Suno', 'score', 'score/salon-gears.mp3',            'Suno v2 — Score (alpha 12 Hz)'),
  ('Quiet Salon',            'Generated by Suno', 'score', 'score/quiet-salon.mp3',            'Suno v2 — Score (alpha 12 Hz)'),
  -- Chapel pair
  ('Stone Chapel Arpeggio',  'Generated by Suno', 'score', 'score/stone-chapel-arpeggio.mp3',  'Suno v2 — Score (alpha 12 Hz)'),
  ('Chapel Light',           'Generated by Suno', 'score', 'score/chapel-light.mp3',           'Suno v2 — Score (alpha 12 Hz)'),
  -- Offering triplet (three Suno variants)
  ('Upward Offering',        'Generated by Suno', 'score', 'score/upward-offering.mp3',        'Suno v2 — Score (alpha 12 Hz)'),
  ('Slow Ascension',         'Generated by Suno', 'score', 'score/slow-ascension.mp3',         'Suno v2 — Score (alpha 12 Hz)'),
  ('Held Offering',          'Generated by Suno', 'score', 'score/held-offering.mp3',          'Suno v2 — Score (alpha 12 Hz)'),
  -- Harpglass pair
  ('Valley of Harpglass',    'Generated by Suno', 'score', 'score/valley-of-harpglass.mp3',    'Suno v2 — Score (alpha 12 Hz)'),
  ('Glass Valley',           'Generated by Suno', 'score', 'score/glass-valley.mp3',           'Suno v2 — Score (alpha 12 Hz)'),
  -- Hearth pair
  ('Warm Little Fire',       'Generated by Suno', 'score', 'score/warm-little-fire.mp3',       'Suno v2 — Score (alpha 12 Hz)'),
  ('Hearth Glow',            'Generated by Suno', 'score', 'score/hearth-glow.mp3',            'Suno v2 — Score (alpha 12 Hz)')
ON CONFLICT (file_path) DO NOTHING;
