-- Session music
--
-- Optional background music during focus sessions. Tracks live in a public
-- Supabase Storage bucket (`session-music`) organised by mood folders that
-- mirror the existing energy taxonomy:
--
--   session-music/deep/    — intense focus (dark ambient, minimal drones)
--   session-music/medium/  — steady work (lofi beats, soft electronic)
--   session-music/light/   — gentle background (piano, nature, classical)
--
-- The `session_tracks` table is the source of truth for metadata + active
-- state. The bucket holds the bytes. Auto-selection logic on the client
-- queries this table filtered by category and picks a random row, then
-- builds a public URL pointing at file_path.
--
-- Why a table at all (vs just listing the bucket)?
-- 1. Soft-delete via is_active without re-uploading.
-- 2. Friendly titles + attribution that don't live in filenames.
-- 3. Weighted selection — bump favourites without uploading duplicates.
-- 4. Future per-track features (duration, BPM, tags) without schema churn.

-- ── 1. Storage bucket ─────────────────────────────────────────────────────

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'session-music',
  'session-music',
  true,                                   -- publicly readable (anyone can stream)
  20971520,                               -- 20 MB / track (~5min @320kbps with headroom)
  ARRAY['audio/mpeg', 'audio/mp3', 'audio/ogg', 'audio/wav', 'audio/x-wav']
)
ON CONFLICT (id) DO UPDATE
  SET public = EXCLUDED.public,
      file_size_limit = EXCLUDED.file_size_limit,
      allowed_mime_types = EXCLUDED.allowed_mime_types;

-- RLS on storage.objects — only admins can write; everyone reads.

DROP POLICY IF EXISTS "session_music_read_all" ON storage.objects;
CREATE POLICY "session_music_read_all"
ON storage.objects FOR SELECT
USING (bucket_id = 'session-music');

DROP POLICY IF EXISTS "session_music_admin_write" ON storage.objects;
CREATE POLICY "session_music_admin_write"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'session-music' AND public.is_admin());

DROP POLICY IF EXISTS "session_music_admin_update" ON storage.objects;
CREATE POLICY "session_music_admin_update"
ON storage.objects FOR UPDATE
USING (bucket_id = 'session-music' AND public.is_admin());

DROP POLICY IF EXISTS "session_music_admin_delete" ON storage.objects;
CREATE POLICY "session_music_admin_delete"
ON storage.objects FOR DELETE
USING (bucket_id = 'session-music' AND public.is_admin());

-- ── 2. session_tracks metadata table ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.session_tracks (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title             text NOT NULL,
  artist            text,                 -- e.g. "Generated by Suno"
  category          text NOT NULL CHECK (category IN ('deep', 'medium', 'light')),
  file_path         text NOT NULL UNIQUE, -- e.g. "deep/01-tunnel-vision.mp3"
  duration_seconds  int,
  attribution       text,                 -- prompt used / licence / credit
  is_active         boolean NOT NULL DEFAULT true,
  sort_weight       int NOT NULL DEFAULT 100,  -- higher = picked more often
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS session_tracks_category_active_idx
  ON public.session_tracks(category, is_active);

-- updated_at trigger
DROP TRIGGER IF EXISTS session_tracks_updated_at ON public.session_tracks;
CREATE TRIGGER session_tracks_updated_at
  BEFORE UPDATE ON public.session_tracks
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS: authenticated users read active rows; admins write everything.

ALTER TABLE public.session_tracks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "session_tracks_read_active" ON public.session_tracks;
CREATE POLICY "session_tracks_read_active"
ON public.session_tracks FOR SELECT
TO authenticated
USING (is_active = true OR public.is_admin());

DROP POLICY IF EXISTS "session_tracks_admin_write" ON public.session_tracks;
CREATE POLICY "session_tracks_admin_write"
ON public.session_tracks FOR INSERT
TO authenticated
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "session_tracks_admin_update" ON public.session_tracks;
CREATE POLICY "session_tracks_admin_update"
ON public.session_tracks FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "session_tracks_admin_delete" ON public.session_tracks;
CREATE POLICY "session_tracks_admin_delete"
ON public.session_tracks FOR DELETE
TO authenticated
USING (public.is_admin());
