-- Add two new music categories: Drive + Score.
--
-- Expands the state-based taxonomy from 6 → 8 categories so we can
-- meet two arrival states that the original 6 didn't serve well:
--
--   ⚡ drive  — Tired but must push through  → Mid-beta 16 Hz
--               External rhythm as fuel (deep house / minimal).
--   🎬 score  — Need gravitas / purposeful   → Alpha 12 Hz
--               Orchestral elevation; the work needs to feel significant.
--
-- 10 tracks per category, mirroring the existing albums. MP3 files
-- live under storage path "drive/" and "score/" in the session-music
-- bucket — same convention as the other six albums.

-- ── 1. Swap the CHECK constraint to include the new categories ────────

ALTER TABLE public.session_tracks
  DROP CONSTRAINT IF EXISTS session_tracks_category_check;

ALTER TABLE public.session_tracks
  ADD CONSTRAINT session_tracks_category_check
  CHECK (category IN ('calm', 'anchor', 'lift', 'flow', 'deep', 'open', 'drive', 'score'));

-- ── 2. Extend music_category_target_hz() ──────────────────────────────

CREATE OR REPLACE FUNCTION public.music_category_target_hz(category text)
RETURNS int
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE category
    WHEN 'calm'   THEN 9     -- Alpha — slow the system down
    WHEN 'anchor' THEN 13    -- Low beta — rhythmic structure to latch onto
    WHEN 'lift'   THEN 10    -- Alpha-beta — gentle activation
    WHEN 'flow'   THEN 14    -- Low beta — deepen into focus
    WHEN 'deep'   THEN 40    -- Gamma — maintain hyperfocus
    WHEN 'open'   THEN 8     -- Theta-alpha — creative daydream zone
    WHEN 'drive'  THEN 16    -- Mid-beta — external rhythm as fuel
    WHEN 'score'  THEN 12    -- Alpha — orchestral gravitas
    ELSE NULL
  END;
$$;

GRANT EXECUTE ON FUNCTION public.music_category_target_hz(text) TO authenticated, anon;

-- ── 3. Seed the 20 tracks ──────────────────────────────────────────────
--
-- File paths follow the same convention used for the first six albums:
--   <category>/NN-slugified-title.mp3
-- on conflict do nothing keeps re-runs idempotent.

INSERT INTO public.session_tracks (title, artist, category, file_path, attribution) VALUES
  ('Grid Work',       'Generated by Suno', 'drive', 'drive/01-grid-work.mp3',       'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Basement Logic',  'Generated by Suno', 'drive', 'drive/02-basement-logic.mp3',  'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Amber Circuit',   'Generated by Suno', 'drive', 'drive/03-amber-circuit.mp3',   'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Sub Meridian',    'Generated by Suno', 'drive', 'drive/04-sub-meridian.mp3',    'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Slow Machinery',  'Generated by Suno', 'drive', 'drive/05-slow-machinery.mp3',  'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Late Session',    'Generated by Suno', 'drive', 'drive/06-late-session.mp3',    'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Phase State',     'Generated by Suno', 'drive', 'drive/07-phase-state.mp3',     'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Carbon Wire',     'Generated by Suno', 'drive', 'drive/08-carbon-wire.mp3',     'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Warm Signal',     'Generated by Suno', 'drive', 'drive/09-warm-signal.mp3',     'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Deep Current',    'Generated by Suno', 'drive', 'drive/10-deep-current.mp3',    'Suno v2 — Drive (mid-beta 16 Hz)'),

  ('Opening Frame',   'Generated by Suno', 'score', 'score/01-opening-frame.mp3',   'Suno v2 — Score (alpha 12 Hz)'),
  ('Vast Interior',   'Generated by Suno', 'score', 'score/02-vast-interior.mp3',   'Suno v2 — Score (alpha 12 Hz)'),
  ('The Atlas',       'Generated by Suno', 'score', 'score/03-the-atlas.mp3',       'Suno v2 — Score (alpha 12 Hz)'),
  ('Slow Magnitude',  'Generated by Suno', 'score', 'score/04-slow-magnitude.mp3',  'Suno v2 — Score (alpha 12 Hz)'),
  ('Meridian',        'Generated by Suno', 'score', 'score/05-meridian.mp3',        'Suno v2 — Score (alpha 12 Hz)'),
  ('Pale Distance',   'Generated by Suno', 'score', 'score/06-pale-distance.mp3',   'Suno v2 — Score (alpha 12 Hz)'),
  ('The Quiet Work',  'Generated by Suno', 'score', 'score/07-the-quiet-work.mp3',  'Suno v2 — Score (alpha 12 Hz)'),
  ('Unseen Hours',    'Generated by Suno', 'score', 'score/08-unseen-hours.mp3',    'Suno v2 — Score (alpha 12 Hz)'),
  ('Continental',     'Generated by Suno', 'score', 'score/09-continental.mp3',     'Suno v2 — Score (alpha 12 Hz)'),
  ('The Weight',      'Generated by Suno', 'score', 'score/10-the-weight.mp3',      'Suno v2 — Score (alpha 12 Hz)')
ON CONFLICT (file_path) DO NOTHING;
