-- Zen album — seed the 32 real tracks.
--
-- `zen` is the East Asian / Japanese instrumental category (shakuhachi, koto,
-- biwa, taiko, plus pan-Asian raga/steppe/gamelan textures) targeting
-- theta–alpha 8 Hz for the creative / daydream mental state.
--
-- 11 prompts came back as two Suno variants each; rather than carry a "(1)"
-- suffix, each sibling is renamed to its own title so the pair reads as two
-- distinct tracks (e.g. Bamboo Breath + Bamboo Wind, Zen Garden + Raked
-- Stones). 10 prompts produced a single track. 22 + 10 = 32.
--
-- Storage prefix: session-music/zen/. Filenames are slugified lowercase +
-- hyphenated (so "Cedar Over Prairie" → cedar-over-prairie.mp3). Upload the
-- MP3s under those names to the `session-music` bucket before users play.

INSERT INTO public.session_tracks (title, artist, category, file_path, attribution) VALUES
  -- Scholar pair
  ('Ancient Scholar''s Reverie', 'Generated by Suno', 'zen', 'zen/ancient-scholars-reverie.mp3',    'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Sage''s Reverie',            'Generated by Suno', 'zen', 'zen/sages-reverie.mp3',               'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- Bamboo breath pair
  ('Bamboo Breath',             'Generated by Suno', 'zen', 'zen/bamboo-breath.mp3',                'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Bamboo Wind',               'Generated by Suno', 'zen', 'zen/bamboo-wind.mp3',                  'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- Cedar pair
  ('Cedar Over Prairie',        'Generated by Suno', 'zen', 'zen/cedar-over-prairie.mp3',           'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Cedar in Mist',             'Generated by Suno', 'zen', 'zen/cedar-in-mist.mp3',                'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- Empty space pair
  ('Empty Space Meditation',    'Generated by Suno', 'zen', 'zen/empty-space-meditation.mp3',       'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Stillness of Emptiness',    'Generated by Suno', 'zen', 'zen/stillness-of-emptiness.mp3',       'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- Garden pair
  ('Garden Whispers',           'Generated by Suno', 'zen', 'zen/garden-whispers.mp3',              'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Temple Garden',             'Generated by Suno', 'zen', 'zen/temple-garden.mp3',                'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- River pair
  ('River''s Thought',          'Generated by Suno', 'zen', 'zen/rivers-thought.mp3',              'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Drifting River',            'Generated by Suno', 'zen', 'zen/drifting-river.mp3',               'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- Silence pair
  ('Silence Speaks',            'Generated by Suno', 'zen', 'zen/silence-speaks.mp3',               'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Quiet Speaks',              'Generated by Suno', 'zen', 'zen/quiet-speaks.mp3',                 'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- Moon pair
  ('Silent Whispers of the Moon','Generated by Suno','zen', 'zen/silent-whispers-of-the-moon.mp3',  'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Moonlit Whisper',           'Generated by Suno', 'zen', 'zen/moonlit-whisper.mp3',              'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- Pine pair
  ('Whispers in the Pine',      'Generated by Suno', 'zen', 'zen/whispers-in-the-pine.mp3',         'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Pine Wind',                 'Generated by Suno', 'zen', 'zen/pine-wind.mp3',                    'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- Winter pair
  ('Winter''s Embrace',         'Generated by Suno', 'zen', 'zen/winters-embrace.mp3',             'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('First Frost',               'Generated by Suno', 'zen', 'zen/first-frost.mp3',                  'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- Zen garden pair
  ('Zen Garden',                'Generated by Suno', 'zen', 'zen/zen-garden.mp3',                   'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Raked Stones',              'Generated by Suno', 'zen', 'zen/raked-stones.mp3',                 'Suno v2 — Zen (theta–alpha 8 Hz)'),
  -- Singles
  ('Bamboo Dawn Raga',          'Generated by Suno', 'zen', 'zen/bamboo-dawn-raga.mp3',             'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Jade Reed Morning',         'Generated by Suno', 'zen', 'zen/jade-reed-morning.mp3',            'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Open Steppe',               'Generated by Suno', 'zen', 'zen/open-steppe.mp3',                  'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Pavilion Xylophone',        'Generated by Suno', 'zen', 'zen/pavilion-xylophone.mp3',           'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Paviliun Perunggu',         'Generated by Suno', 'zen', 'zen/paviliun-perunggu.mp3',            'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Raga Dawn Halo',            'Generated by Suno', 'zen', 'zen/raga-dawn-halo.mp3',               'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Silk String Room',          'Generated by Suno', 'zen', 'zen/silk-string-room.mp3',             'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Stone Horn Stillness',      'Generated by Suno', 'zen', 'zen/stone-horn-stillness.mp3',         'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Water Silk',                'Generated by Suno', 'zen', 'zen/water-silk.mp3',                   'Suno v2 — Zen (theta–alpha 8 Hz)'),
  ('Zen Biwa',                  'Generated by Suno', 'zen', 'zen/zen-biwa.mp3',                     'Suno v2 — Zen (theta–alpha 8 Hz)')
ON CONFLICT (file_path) DO NOTHING;
