-- Drive album — realign existing tracks + add thematic siblings.
--
-- Migration 20260527000007 seeded 10 Drive tracks with numeric-prefix
-- file paths (e.g. `drive/01-grid-work.mp3`). The user uploaded the MP3s
-- to Supabase Storage using pretty human-readable names ("Grid Work.mp3")
-- — same convention they used for Dusk. Two things to fix:
--
--   1. Realign the 10 existing rows' file_path values to the actual
--      Storage filenames so getPublicUrl() resolves correctly.
--   2. Add 10 thematic sibling tracks (one per original) so the album
--      doubles to 20, matching how Dusk and Score scaled up. Sibling
--      names share the krautrock / late-night-focus / propulsive vibe.
--
-- Spaces in file_path are intentional — Supabase Storage handles them
-- (URL-encodes to %20 on read). See migration 20260527000014 for the
-- same pattern applied to Dusk.

-- ── 1. Realign existing rows — drop the NN- prefix, use pretty names ──

UPDATE public.session_tracks SET file_path = 'drive/Grid Work.mp3'         WHERE file_path = 'drive/01-grid-work.mp3';
UPDATE public.session_tracks SET file_path = 'drive/Basement Logic.mp3'    WHERE file_path = 'drive/02-basement-logic.mp3';
UPDATE public.session_tracks SET file_path = 'drive/Amber Circuit.mp3'     WHERE file_path = 'drive/03-amber-circuit.mp3';
UPDATE public.session_tracks SET file_path = 'drive/Sub Meridian.mp3'      WHERE file_path = 'drive/04-sub-meridian.mp3';
UPDATE public.session_tracks SET file_path = 'drive/Slow Machinery.mp3'    WHERE file_path = 'drive/05-slow-machinery.mp3';
UPDATE public.session_tracks SET file_path = 'drive/Late Session.mp3'      WHERE file_path = 'drive/06-late-session.mp3';
UPDATE public.session_tracks SET file_path = 'drive/Phase State.mp3'       WHERE file_path = 'drive/07-phase-state.mp3';
UPDATE public.session_tracks SET file_path = 'drive/Carbon Wire.mp3'       WHERE file_path = 'drive/08-carbon-wire.mp3';
UPDATE public.session_tracks SET file_path = 'drive/Warm Signal.mp3'       WHERE file_path = 'drive/09-warm-signal.mp3';
UPDATE public.session_tracks SET file_path = 'drive/Deep Current.mp3'      WHERE file_path = 'drive/10-deep-current.mp3';

-- ── 2. Insert thematic siblings ───────────────────────────────────────
-- Each sibling pairs with its original by concept: same texture, fresh
-- title. Generation notes mirror the original tracks for consistency.

INSERT INTO public.session_tracks (title, artist, category, file_path, attribution) VALUES
  ('Lattice Work',     'Generated by Suno', 'drive', 'drive/Lattice Work.mp3',     'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Cellar Reason',    'Generated by Suno', 'drive', 'drive/Cellar Reason.mp3',    'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Bronze Loop',      'Generated by Suno', 'drive', 'drive/Bronze Loop.mp3',      'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Sub Equator',      'Generated by Suno', 'drive', 'drive/Sub Equator.mp3',      'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Slow Engine',      'Generated by Suno', 'drive', 'drive/Slow Engine.mp3',      'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('After Hours',      'Generated by Suno', 'drive', 'drive/After Hours.mp3',      'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Phase Drift',      'Generated by Suno', 'drive', 'drive/Phase Drift.mp3',      'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Copper Filament',  'Generated by Suno', 'drive', 'drive/Copper Filament.mp3',  'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Steady Pulse',     'Generated by Suno', 'drive', 'drive/Steady Pulse.mp3',     'Suno v2 — Drive (mid-beta 16 Hz)'),
  ('Undertow',         'Generated by Suno', 'drive', 'drive/Undertow.mp3',         'Suno v2 — Drive (mid-beta 16 Hz)')
ON CONFLICT (file_path) DO NOTHING;
