/*
  # Add Constraint: AI Recipes Cannot Have Creator

  ## Overview
  Adds a database-level constraint to ensure AI-generated recipes never have a created_by value.
  This prevents accidental assignment of ownership to AI-generated content.

  ## Rationale
  - AI recipes are generated by the system, not by users
  - created_by should be NULL for AI recipes
  - This constraint provides database-level safety

  ## Changes
  - Add CHECK constraint: source_type != 'ai' OR created_by IS NULL
*/

-- Add constraint to ensure AI recipes never have a creator
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ai_recipes_no_creator'
  ) THEN
    ALTER TABLE recipes
    ADD CONSTRAINT ai_recipes_no_creator
    CHECK (
      source_type != 'ai' OR created_by IS NULL
    );
  END IF;
END $$;

-- Add comment explaining the constraint
COMMENT ON CONSTRAINT ai_recipes_no_creator ON recipes IS 
  'Ensures AI-generated recipes (source_type = ''ai'') never have a created_by value. AI recipes are system-generated and should not be attributed to users.';
