/*
  # Create Mind Mesh V2 Telemetry System

  1. New Tables
    - `mind_mesh_telemetry_events`
      - `id` (uuid, primary key)
      - `workspace_id` (uuid, references mindmesh_workspaces)
      - `user_id` (uuid, references auth.users)
      - `event_type` (text, allowed telemetry event types)
      - `timestamp` (timestamptz, when event occurred)
      - `meta` (jsonb, allowed metadata fields only)
      - `created_at` (timestamptz, when record was created)

  2. Security
    - Enable RLS on `mind_mesh_telemetry_events` table
    - Users can read their own telemetry
    - Only authenticated users can insert telemetry

  3. Indexes
    - `(workspace_id, timestamp desc)` - for workspace queries
    - `(user_id, timestamp desc)` - for user queries
    - `(event_type, timestamp desc)` - for event type analysis

  4. Privacy Contract
    - Telemetry NEVER captures content (title, body, text)
    - Telemetry NEVER captures references (IDs to Guardrails entities)
    - Telemetry NEVER captures relationships (container IDs, node endpoints)
    - Telemetry ONLY captures structural patterns and behavior
*/

-- Create telemetry events table
CREATE TABLE IF NOT EXISTS mind_mesh_telemetry_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES mindmesh_workspaces(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  timestamp timestamptz NOT NULL,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE mind_mesh_telemetry_events ENABLE ROW LEVEL SECURITY;

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_mm_telemetry_workspace_timestamp
  ON mind_mesh_telemetry_events(workspace_id, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_mm_telemetry_user_timestamp
  ON mind_mesh_telemetry_events(user_id, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_mm_telemetry_event_type_timestamp
  ON mind_mesh_telemetry_events(event_type, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_mm_telemetry_created_at
  ON mind_mesh_telemetry_events(created_at DESC);

-- Index for date-range queries
CREATE INDEX IF NOT EXISTS idx_mm_telemetry_timestamp_only
  ON mind_mesh_telemetry_events(timestamp DESC);

-- RLS Policies

-- Users can insert their own telemetry events
CREATE POLICY "Users can insert own telemetry"
  ON mind_mesh_telemetry_events
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Users can read their own telemetry events
CREATE POLICY "Users can read own telemetry"
  ON mind_mesh_telemetry_events
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Comment on table
COMMENT ON TABLE mind_mesh_telemetry_events IS
  'Privacy-preserving telemetry events for Mind Mesh V2. Never captures content, references, or relationships. Only structural patterns and behavior.';

-- Comment on columns
COMMENT ON COLUMN mind_mesh_telemetry_events.event_type IS
  'Telemetry event type. Must be from allowed list (ContainerCreated, ContainerActivated, etc). See telemetry/types.ts for complete list.';

COMMENT ON COLUMN mind_mesh_telemetry_events.meta IS
  'Allowed metadata fields only: containerType, relationshipType, direction, isGhost, isAutoGenerated, activationReason, sessionDurationMinutes, entityCount. NO content, references, or IDs allowed.';

COMMENT ON COLUMN mind_mesh_telemetry_events.timestamp IS
  'When the event occurred (event time, not insert time). Use for temporal analysis.';

COMMENT ON COLUMN mind_mesh_telemetry_events.created_at IS
  'When the record was inserted into database (insert time). Use for auditing.';
